/*
 * HDRUK Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.gatewayapi.api;

import uk.ac.hdruk.gatewayapi.ApiException;
import uk.ac.hdruk.gatewayapi.model.CreateAliases500Response;
import uk.ac.hdruk.gatewayapi.model.CreateCsat422Response;
import uk.ac.hdruk.gatewayapi.model.CreateCsatRequest;
import uk.ac.hdruk.gatewayapi.model.DeleteAliases200Response;
import uk.ac.hdruk.gatewayapi.model.EditCsat200Response;
import uk.ac.hdruk.gatewayapi.model.EditCsatRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CustomerSatisfactionApi
 */
@Disabled
public class CustomerSatisfactionApiTest {

    private final CustomerSatisfactionApi api = new CustomerSatisfactionApi();

    /**
     * Create Customer Satisfaction Score
     *
     * Creates a customer satisfaction score between 0 and 5
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createCsatTest() throws ApiException {
        CreateCsatRequest createCsatRequest = null;
        DeleteAliases200Response response = api.createCsat(createCsatRequest);
        // TODO: test validations
    }

    /**
     * Update Customer Satisfaction Description
     *
     * Update a description for a satisfaction score entry
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void editCsatTest() throws ApiException {
        Integer id = null;
        EditCsatRequest editCsatRequest = null;
        EditCsat200Response response = api.editCsat(id, editCsatRequest);
        // TODO: test validations
    }

}
