/*
 * HDRUK Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.gatewayapi.api;

import uk.ac.hdruk.gatewayapi.ApiException;
import uk.ac.hdruk.gatewayapi.model.FetchDataProviderColl200Response;
import uk.ac.hdruk.gatewayapi.model.FetchDataProviderCollSummary200Response;
import uk.ac.hdruk.gatewayapi.model.FetchDataProviderColls200Response;
import uk.ac.hdruk.gatewayapi.model.UpdateApplications404Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DataProviderCollApi
 */
@Disabled
public class DataProviderCollApiTest {

    private final DataProviderCollApi api = new DataProviderCollApi();

    /**
     * DataProviderColl@show
     *
     * Return a single DataProviderColl
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void fetchDataProviderCollTest() throws ApiException {
        Integer id = null;
        FetchDataProviderColl200Response response = api.fetchDataProviderColl(id);
        // TODO: test validations
    }

    /**
     * DataProviderColl@showSummary
     *
     * Return a single DataProviderColl - summary
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void fetchDataProviderCollSummaryTest() throws ApiException {
        Integer id = null;
        FetchDataProviderCollSummary200Response response = api.fetchDataProviderCollSummary(id);
        // TODO: test validations
    }

    /**
     * DataProviderColl@index
     *
     * Returns a list of DataProviderColls enabled on the system
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void fetchDataProviderCollsTest() throws ApiException {
        Integer perPage = null;
        FetchDataProviderColls200Response response = api.fetchDataProviderColls(perPage);
        // TODO: test validations
    }

}
