/*
 * HDRUK Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.gatewayapi.api;

import uk.ac.hdruk.gatewayapi.ApiException;
import uk.ac.hdruk.gatewayapi.model.CreateApplications500Response;
import uk.ac.hdruk.gatewayapi.model.CreateDarIntegration201Response;
import uk.ac.hdruk.gatewayapi.model.DatasetsTestRequest;
import uk.ac.hdruk.gatewayapi.model.FetchAllDarIntegrations401Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for IntegrationsDatasetsTestApi
 */
@Disabled
public class IntegrationsDatasetsTestApiTest {

    private final IntegrationsDatasetsTestApi api = new IntegrationsDatasetsTestApi();

    /**
     * IntegrationDatasetController@datasetTest
     *
     * Integrations datasets test
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void integrationsDatasetsTestTest() throws ApiException {
        DatasetsTestRequest datasetsTestRequest = null;
        CreateDarIntegration201Response response = api.integrationsDatasetsTest(datasetsTestRequest);
        // TODO: test validations
    }

}
