/*
 * HDRUK Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.gatewayapi.api;

import uk.ac.hdruk.gatewayapi.ApiException;
import uk.ac.hdruk.gatewayapi.model.FetchDatasetLinkCheckResultsV2200Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for NightlyDatasetTestsApi
 */
@Disabled
public class NightlyDatasetTestsApiTest {

    private final NightlyDatasetTestsApi api = new NightlyDatasetTestsApi();

    /**
     * NightlyDatasetTestController@index
     *
     * Get the results of the nightly dataset reachability check, with a summary and a list of failures
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void fetchNightlyDatasetTestsV2Test() throws ApiException {
        FetchDatasetLinkCheckResultsV2200Response response = api.fetchNightlyDatasetTestsV2();
        // TODO: test validations
    }

}
