/*
 * HDRUK Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.gatewayapi.api;

import uk.ac.hdruk.gatewayapi.ApiException;
import uk.ac.hdruk.gatewayapi.model.CreateAliases500Response;
import uk.ac.hdruk.gatewayapi.model.CreateCategories200Response;
import uk.ac.hdruk.gatewayapi.model.CreateQuestionBankQuestionRequest;
import uk.ac.hdruk.gatewayapi.model.DeleteAliases200Response;
import uk.ac.hdruk.gatewayapi.model.EditQuestionBankQuestionRequest;
import uk.ac.hdruk.gatewayapi.model.FetchAliases404Response;
import uk.ac.hdruk.gatewayapi.model.FetchCustomQuestionBankQuestions200Response;
import uk.ac.hdruk.gatewayapi.model.FetchQuestionBankQuestion200Response;
import uk.ac.hdruk.gatewayapi.model.FetchQuestionBankQuestionVersion200Response;
import uk.ac.hdruk.gatewayapi.model.FetchQuestionBankQuestions200Response;
import uk.ac.hdruk.gatewayapi.model.FetchStandardQuestionBankQuestions200Response;
import uk.ac.hdruk.gatewayapi.model.FetchTeamQuestionBankQuestionsBySection200Response;
import uk.ac.hdruk.gatewayapi.model.UpdateQuestionBankQuestion200Response;
import uk.ac.hdruk.gatewayapi.model.UpdateQuestionBankQuestionRequest;
import uk.ac.hdruk.gatewayapi.model.UpdateQuestionBankQuestionStatus200Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for QuestionBankApi
 */
@Disabled
public class QuestionBankApiTest {

    private final QuestionBankApi api = new QuestionBankApi();

    /**
     * QuestionBank@store
     *
     * Create a new system question bank question with FE-helpful input format
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createQuestionBankQuestionTest() throws ApiException {
        CreateQuestionBankQuestionRequest createQuestionBankQuestionRequest = null;
        CreateCategories200Response response = api.createQuestionBankQuestion(createQuestionBankQuestionRequest);
        // TODO: test validations
    }

    /**
     * QuestionBank@destroy
     *
     * Delete a system question bank question
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteQuestionBankQuestionTest() throws ApiException {
        Integer id = null;
        DeleteAliases200Response response = api.deleteQuestionBankQuestion(id);
        // TODO: test validations
    }

    /**
     * QuestionBank@destroyFile
     *
     * Download a system question bank question
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void downloadQuestionBankQuestionFileTest() throws ApiException {
        Integer id = null;
        Integer fileId = null;
        DeleteAliases200Response response = api.downloadQuestionBankQuestionFile(id, fileId);
        // TODO: test validations
    }

    /**
     * QuestionBank@update
     *
     * Edit a system question bank question - use this for parents and children separately
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void editQuestionBankQuestionTest() throws ApiException {
        Integer id = null;
        EditQuestionBankQuestionRequest editQuestionBankQuestionRequest = null;
        UpdateQuestionBankQuestion200Response response = api.editQuestionBankQuestion(id, editQuestionBankQuestionRequest);
        // TODO: test validations
    }

    /**
     * QuestionBank@indexArchived
     *
     * List of archived question bank questions
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void fetchArchivedQuestionBankQuestionsTest() throws ApiException {
        Integer sectionId = null;
        Integer isChild = null;
        Integer perPage = null;
        Integer page = null;
        FetchQuestionBankQuestions200Response response = api.fetchArchivedQuestionBankQuestions(sectionId, isChild, perPage, page);
        // TODO: test validations
    }

    /**
     * QuestionBank@indexCustom
     *
     * List of custom question bank questions
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void fetchCustomQuestionBankQuestionsTest() throws ApiException {
        Integer sectionId = null;
        Integer isChild = null;
        Integer perPage = null;
        Integer page = null;
        FetchCustomQuestionBankQuestions200Response response = api.fetchCustomQuestionBankQuestions(sectionId, isChild, perPage, page);
        // TODO: test validations
    }

    /**
     * QuestionBank@show
     *
     * Return the latest question bank question version for the supplied question id, in an FE-friendly format
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void fetchQuestionBankQuestionTest() throws ApiException {
        Integer id = null;
        FetchQuestionBankQuestion200Response response = api.fetchQuestionBankQuestion(id);
        // TODO: test validations
    }

    /**
     * QuestionBank@showVersion
     *
     * Return a single system question bank question version
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void fetchQuestionBankQuestionVersionTest() throws ApiException {
        Integer id = null;
        FetchQuestionBankQuestionVersion200Response response = api.fetchQuestionBankQuestionVersion(id);
        // TODO: test validations
    }

    /**
     * QuestionBank@index
     *
     * List of question bank questions
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void fetchQuestionBankQuestionsTest() throws ApiException {
        Integer sectionId = null;
        Integer isChild = null;
        Integer perPage = null;
        Integer page = null;
        FetchQuestionBankQuestions200Response response = api.fetchQuestionBankQuestions(sectionId, isChild, perPage, page);
        // TODO: test validations
    }

    /**
     * QuestionBank@indexStandard
     *
     * List of standard question bank questions
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void fetchStandardQuestionBankQuestionsTest() throws ApiException {
        Integer sectionId = null;
        Integer isChild = null;
        Integer perPage = null;
        Integer page = null;
        FetchStandardQuestionBankQuestions200Response response = api.fetchStandardQuestionBankQuestions(sectionId, isChild, perPage, page);
        // TODO: test validations
    }

    /**
     * TeamQuestionBank@indexBySection
     *
     * List of question bank questions by section
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void fetchTeamQuestionBankQuestionsBySectionTest() throws ApiException {
        Integer teamId = null;
        Integer sectionId = null;
        Integer isChild = null;
        FetchTeamQuestionBankQuestionsBySection200Response response = api.fetchTeamQuestionBankQuestionsBySection(teamId, sectionId, isChild);
        // TODO: test validations
    }

    /**
     * QuestionBank@update
     *
     * Update a system question bank question - children and their versions are updated through parents
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateQuestionBankQuestionTest() throws ApiException {
        Integer id = null;
        UpdateQuestionBankQuestionRequest updateQuestionBankQuestionRequest = null;
        UpdateQuestionBankQuestion200Response response = api.updateQuestionBankQuestion(id, updateQuestionBankQuestionRequest);
        // TODO: test validations
    }

    /**
     * QuestionBank@updateStatus
     *
     * Lock, unlock, archive or unarchive a question bank question
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateQuestionBankQuestionStatusTest() throws ApiException {
        Integer id = null;
        String status = null;
        UpdateQuestionBankQuestionStatus200Response response = api.updateQuestionBankQuestionStatus(id, status);
        // TODO: test validations
    }

}
