/*
 * HDRUK Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.gatewayapi.api;

import uk.ac.hdruk.gatewayapi.ApiException;
import uk.ac.hdruk.gatewayapi.model.SearchSimilarDatasets200Response;
import uk.ac.hdruk.gatewayapi.model.SearchSimilarDatasetsRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SearchSimilarDatasetsApi
 */
@Disabled
public class SearchSimilarDatasetsApiTest {

    private final SearchSimilarDatasetsApi api = new SearchSimilarDatasetsApi();

    /**
     * Search@similarDatasets
     *
     * Returns top three gateway datasets most similar to the provided dataset
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void searchSimilarDatasetsTest() throws ApiException {
        SearchSimilarDatasetsRequest searchSimilarDatasetsRequest = null;
        SearchSimilarDatasets200Response response = api.searchSimilarDatasets(searchSimilarDatasetsRequest);
        // TODO: test validations
    }

}
