/*
 * HDRUK Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.gatewayapi.api;

import uk.ac.hdruk.gatewayapi.ApiException;
import uk.ac.hdruk.gatewayapi.model.SearchDataCustodianNetworks200Response;
import uk.ac.hdruk.gatewayapi.model.SearchDataCustodianNetworksRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SearchDataCustodianNetworksApi
 */
@Disabled
public class SearchDataCustodianNetworksApiTest {

    private final SearchDataCustodianNetworksApi api = new SearchDataCustodianNetworksApi();

    /**
     * Search@data_custodian_networks
     *
     * Returns gateway data custodian networks related to the provided query term(s)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void searchDataCustodianNetworksTest() throws ApiException {
        SearchDataCustodianNetworksRequest searchDataCustodianNetworksRequest = null;
        String sort = null;
        String direction = null;
        SearchDataCustodianNetworks200Response response = api.searchDataCustodianNetworks(searchDataCustodianNetworksRequest, sort, direction);
        // TODO: test validations
    }

}
