/*
 * HDRUK Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.gatewayapi.api;

import uk.ac.hdruk.gatewayapi.ApiException;
import uk.ac.hdruk.gatewayapi.model.SearchPublications200Response;
import uk.ac.hdruk.gatewayapi.model.SearchPublicationsByDoi200Response;
import uk.ac.hdruk.gatewayapi.model.SearchPublicationsByDoiRequest;
import uk.ac.hdruk.gatewayapi.model.SearchPublicationsRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SearchPublicationsApi
 */
@Disabled
public class SearchPublicationsApiTest {

    private final SearchPublicationsApi api = new SearchPublicationsApi();

    /**
     * Search@publications
     *
     * Returns gateway publications related to the provided query term(s)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void searchPublicationsTest() throws ApiException {
        SearchPublicationsRequest searchPublicationsRequest = null;
        String sort = null;
        String direction = null;
        String source = null;
        SearchPublications200Response response = api.searchPublications(searchPublicationsRequest, sort, direction, source);
        // TODO: test validations
    }

    /**
     * Search@publications
     *
     * Returns publications from EuropePMC matching a give DOI
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void searchPublicationsByDoiTest() throws ApiException {
        SearchPublicationsByDoiRequest searchPublicationsByDoiRequest = null;
        SearchPublicationsByDoi200Response response = api.searchPublicationsByDoi(searchPublicationsByDoiRequest);
        // TODO: test validations
    }

}
