/*
 * HDRUK Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.gatewayapi.api;

import uk.ac.hdruk.gatewayapi.ApiException;
import uk.ac.hdruk.gatewayapi.model.CreateWidget201Response;
import uk.ac.hdruk.gatewayapi.model.ExportDatasetMetadata400Response;
import uk.ac.hdruk.gatewayapi.model.FetchCollectionsViewsV3200Response;
import uk.ac.hdruk.gatewayapi.model.FetchDashboardDownloadCsvV3500Response;
import uk.ac.hdruk.gatewayapi.model.FetchDatasetViews360V3200Response;
import uk.ac.hdruk.gatewayapi.model.FetchDatasetViewsTopV3200Response;
import uk.ac.hdruk.gatewayapi.model.FetchEntitiesCountV3200Response;
import java.io.File;
import java.time.LocalDate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TeamDashboardApi
 */
@Disabled
public class TeamDashboardApiTest {

    private final TeamDashboardApi api = new TeamDashboardApi();

    /**
     * TeamDashboardController@collectionViews
     *
     * Get count of a collection views for a team
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void fetchCollectionsViewsV3Test() throws ApiException {
        Integer id = null;
        LocalDate startDate = null;
        LocalDate endDate = null;
        FetchCollectionsViewsV3200Response response = api.fetchCollectionsViewsV3(id, startDate, endDate);
        // TODO: test validations
    }

    /**
     * DataAccessDashboardController@getApplicationTimeline
     *
     * Get Dar applications timeline for a team
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void fetchDarApplicationsApplicationTimelineV3Test() throws ApiException {
        Integer id = null;
        LocalDate startDate = null;
        LocalDate endDate = null;
        CreateWidget201Response response = api.fetchDarApplicationsApplicationTimelineV3(id, startDate, endDate);
        // TODO: test validations
    }

    /**
     * DataAccessDashboardController@getAverageTimeToApproval
     *
     * Get Dar applications average time to approval for a team
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void fetchDarApplicationsAverageTimeToApprovalV3Test() throws ApiException {
        Integer id = null;
        LocalDate startDate = null;
        LocalDate endDate = null;
        CreateWidget201Response response = api.fetchDarApplicationsAverageTimeToApprovalV3(id, startDate, endDate);
        // TODO: test validations
    }

    /**
     * DataAccessDashboardController@getApplicationStatus
     *
     * Get Dar applications current status for a team
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void fetchDarApplicationsCurrentStatusV3Test() throws ApiException {
        Integer id = null;
        LocalDate startDate = null;
        LocalDate endDate = null;
        CreateWidget201Response response = api.fetchDarApplicationsCurrentStatusV3(id, startDate, endDate);
        // TODO: test validations
    }

    /**
     * DataAccessDashboardController@exportDashboardCsv
     *
     * Get Dar applications dashboard export csv for a team
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void fetchDarApplicationsDashboardExportCsvV3Test() throws ApiException {
        Integer id = null;
        LocalDate startDate = null;
        LocalDate endDate = null;
        CreateWidget201Response response = api.fetchDarApplicationsDashboardExportCsvV3(id, startDate, endDate);
        // TODO: test validations
    }

    /**
     * DataAccessDashboardController@exportRequiredActionsCsv
     *
     * Get Dar applications dashboard timeline export csv for a team
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void fetchDarApplicationsDashboardRequiredActionsExportCsvV3Test() throws ApiException {
        Integer id = null;
        CreateWidget201Response response = api.fetchDarApplicationsDashboardRequiredActionsExportCsvV3(id);
        // TODO: test validations
    }

    /**
     * DataAccessDashboardController@exportDashboardTimelineCsv
     *
     * Get Dar applications dashboard timeline export csv for a team
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void fetchDarApplicationsDashboardTimelineExportCsvV3Test() throws ApiException {
        Integer id = null;
        LocalDate startDate = null;
        LocalDate endDate = null;
        CreateWidget201Response response = api.fetchDarApplicationsDashboardTimelineExportCsvV3(id, startDate, endDate);
        // TODO: test validations
    }

    /**
     * DataAccessDashboardController@getRequiredActions
     *
     * Get Dar applications required actions for a team
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void fetchDarApplicationsRequiredActionsV3Test() throws ApiException {
        Integer id = null;
        LocalDate startDate = null;
        LocalDate endDate = null;
        CreateWidget201Response response = api.fetchDarApplicationsRequiredActionsV3(id, startDate, endDate);
        // TODO: test validations
    }

    /**
     * DataAccessDashboardController@getMyApplications
     *
     * Get Dar applications for a team
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void fetchDarMyApplicationsV3Test() throws ApiException {
        Integer id = null;
        LocalDate startDate = null;
        LocalDate endDate = null;
        CreateWidget201Response response = api.fetchDarMyApplicationsV3(id, startDate, endDate);
        // TODO: test validations
    }

    /**
     * TeamDashboardController@downloadCsv
     *
     * Download dashboard data custodian in csv format
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void fetchDashboardDownloadCsvV3Test() throws ApiException {
        Integer id = null;
        LocalDate startDate = null;
        LocalDate endDate = null;
        File response = api.fetchDashboardDownloadCsvV3(id, startDate, endDate);
        // TODO: test validations
    }

    /**
     * TeamDashboardController@datacustodianViews
     *
     * Get count of a data custodian views for a team
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void fetchDataCustodiansViewsV3Test() throws ApiException {
        Integer id = null;
        LocalDate startDate = null;
        LocalDate endDate = null;
        FetchCollectionsViewsV3200Response response = api.fetchDataCustodiansViewsV3(id, startDate, endDate);
        // TODO: test validations
    }

    /**
     * TeamDashboardController@datasetViews360
     *
     * Get count of a datasets views 360 for a team
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void fetchDatasetViews360V3Test() throws ApiException {
        Integer id = null;
        LocalDate startDate = null;
        LocalDate endDate = null;
        FetchDatasetViews360V3200Response response = api.fetchDatasetViews360V3(id, startDate, endDate);
        // TODO: test validations
    }

    /**
     * TeamDashboardController@datasetViewsTop
     *
     * Get count of a datasets views top for a team
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void fetchDatasetViewsTopV3Test() throws ApiException {
        Integer id = null;
        LocalDate startDate = null;
        LocalDate endDate = null;
        FetchDatasetViewsTopV3200Response response = api.fetchDatasetViewsTopV3(id, startDate, endDate);
        // TODO: test validations
    }

    /**
     * TeamDashboardController@entityCount
     *
     * Get count of a specific entity for a team
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void fetchEntitiesCountV3Test() throws ApiException {
        Integer id = null;
        String entity = null;
        LocalDate startDate = null;
        LocalDate endDate = null;
        FetchEntitiesCountV3200Response response = api.fetchEntitiesCountV3(id, entity, startDate, endDate);
        // TODO: test validations
    }

}
