/*
 * HDRUK Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.gatewayapi.api;

import uk.ac.hdruk.gatewayapi.ApiException;
import uk.ac.hdruk.gatewayapi.model.CountUniqueFieldsCollections200Response;
import uk.ac.hdruk.gatewayapi.model.CreateAliases500Response;
import uk.ac.hdruk.gatewayapi.model.CreateCategories200Response;
import uk.ac.hdruk.gatewayapi.model.CreateUserDarApplicationAnswersRequest;
import uk.ac.hdruk.gatewayapi.model.FetchAliases404Response;
import uk.ac.hdruk.gatewayapi.model.FetchTeamDarApplication200Response;
import uk.ac.hdruk.gatewayapi.model.FetchTeamDarApplicationAnswers200Response;
import uk.ac.hdruk.gatewayapi.model.FetchTeamDarApplications200Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserDataAccessApplicationApi
 */
@Disabled
public class UserDataAccessApplicationApiTest {

    private final UserDataAccessApplicationApi api = new UserDataAccessApplicationApi();

    /**
     * UserDataAccessApplicationController@allCounts
     *
     * Get Counts for all status fields in the model
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void countAllUserDarApplicationsTest() throws ApiException {
        Integer userId = null;
        CountUniqueFieldsCollections200Response response = api.countAllUserDarApplications(userId);
        // TODO: test validations
    }

    /**
     * UserDataAccessApplicationController@count
     *
     * Get Counts for distinct entries of a field in the model
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void countUserDarApplicationsByFieldTest() throws ApiException {
        Integer userId = null;
        String field = null;
        CountUniqueFieldsCollections200Response response = api.countUserDarApplicationsByField(userId, field);
        // TODO: test validations
    }

    /**
     * UserDataAccessApplication@storeAnswers
     *
     * Add answers to the user&#39;s DAR application
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createUserDarApplicationAnswersTest() throws ApiException {
        Integer userId = null;
        Integer id = null;
        CreateUserDarApplicationAnswersRequest createUserDarApplicationAnswersRequest = null;
        CreateCategories200Response response = api.createUserDarApplicationAnswers(userId, id, createUserDarApplicationAnswersRequest);
        // TODO: test validations
    }

    /**
     * UserDataAccessApplicationController@showAnswers
     *
     * Return answers from the user&#39;s DAR application
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void fetchUserDarApplicationAnswersTest() throws ApiException {
        Integer userId = null;
        Integer id = null;
        FetchTeamDarApplicationAnswers200Response response = api.fetchUserDarApplicationAnswers(userId, id);
        // TODO: test validations
    }

    /**
     * UserDataAccessApplicationController@show
     *
     * Return a DAR application belonging to the user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void fetchUserDarApplicationDetailsTest() throws ApiException {
        Integer userId = null;
        Integer id = null;
        FetchTeamDarApplication200Response response = api.fetchUserDarApplicationDetails(userId, id);
        // TODO: test validations
    }

    /**
     * UserDataAccessApplicationController@showHeader
     *
     * Get header information about a specific DAR
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void fetchUserDarApplicationHeaderTest() throws ApiException {
        Integer userId = null;
        Integer id = null;
        FetchTeamDarApplication200Response response = api.fetchUserDarApplicationHeader(userId, id);
        // TODO: test validations
    }

    /**
     * UserDataAccessApplicationController@index
     *
     * List of dar applications belonging to a user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void fetchUserDarApplicationsTest() throws ApiException {
        Integer userId = null;
        FetchTeamDarApplications200Response response = api.fetchUserDarApplications(userId);
        // TODO: test validations
    }

}
