/*
 * HDRUK Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.gatewayapi.api;

import uk.ac.hdruk.gatewayapi.ApiCallback;
import uk.ac.hdruk.gatewayapi.ApiClient;
import uk.ac.hdruk.gatewayapi.ApiException;
import uk.ac.hdruk.gatewayapi.ApiResponse;
import uk.ac.hdruk.gatewayapi.Configuration;
import uk.ac.hdruk.gatewayapi.Pair;
import uk.ac.hdruk.gatewayapi.ProgressRequestBody;
import uk.ac.hdruk.gatewayapi.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import uk.ac.hdruk.gatewayapi.model.CreateApplications500Response;
import uk.ac.hdruk.gatewayapi.model.CreateDarIntegration201Response;
import uk.ac.hdruk.gatewayapi.model.CreateFederationTeamRequest;
import uk.ac.hdruk.gatewayapi.model.DeleteFederation200Response;
import uk.ac.hdruk.gatewayapi.model.DeleteFederation404Response;
import uk.ac.hdruk.gatewayapi.model.FetchAllDarIntegrations401Response;
import uk.ac.hdruk.gatewayapi.model.GetFederationByFederationIdAndTeamId200Response;
import uk.ac.hdruk.gatewayapi.model.GetFederationHistory200Response;
import uk.ac.hdruk.gatewayapi.model.GetFederationTeamId200Response;
import uk.ac.hdruk.gatewayapi.model.TestFederation200Response;
import uk.ac.hdruk.gatewayapi.model.UpdateFederationTeamRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TeamFederationsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public TeamFederationsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public TeamFederationsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for createFederationTeam
     * @param teamId team id (required)
     * @param createFederationTeamRequest Pass user credentials (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Created </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createFederationTeamCall(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull CreateFederationTeamRequest createFederationTeamRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createFederationTeamRequest;

        // create path and map variables
        String localVarPath = "/api/v1/teams/{teamId}/federations"
            .replace("{" + "teamId" + "}", localVarApiClient.escapeString(teamId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createFederationTeamValidateBeforeCall(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull CreateFederationTeamRequest createFederationTeamRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'teamId' is set
        if (teamId == null) {
            throw new ApiException("Missing the required parameter 'teamId' when calling createFederationTeam(Async)");
        }

        // verify the required parameter 'createFederationTeamRequest' is set
        if (createFederationTeamRequest == null) {
            throw new ApiException("Missing the required parameter 'createFederationTeamRequest' when calling createFederationTeam(Async)");
        }

        return createFederationTeamCall(teamId, createFederationTeamRequest, _callback);

    }

    /**
     * FederationController@store
     * Create federation
     * @param teamId team id (required)
     * @param createFederationTeamRequest Pass user credentials (required)
     * @return CreateDarIntegration201Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Created </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public CreateDarIntegration201Response createFederationTeam(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull CreateFederationTeamRequest createFederationTeamRequest) throws ApiException {
        ApiResponse<CreateDarIntegration201Response> localVarResp = createFederationTeamWithHttpInfo(teamId, createFederationTeamRequest);
        return localVarResp.getData();
    }

    /**
     * FederationController@store
     * Create federation
     * @param teamId team id (required)
     * @param createFederationTeamRequest Pass user credentials (required)
     * @return ApiResponse&lt;CreateDarIntegration201Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Created </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CreateDarIntegration201Response> createFederationTeamWithHttpInfo(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull CreateFederationTeamRequest createFederationTeamRequest) throws ApiException {
        okhttp3.Call localVarCall = createFederationTeamValidateBeforeCall(teamId, createFederationTeamRequest, null);
        Type localVarReturnType = new TypeToken<CreateDarIntegration201Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * FederationController@store (asynchronously)
     * Create federation
     * @param teamId team id (required)
     * @param createFederationTeamRequest Pass user credentials (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Created </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createFederationTeamAsync(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull CreateFederationTeamRequest createFederationTeamRequest, final ApiCallback<CreateDarIntegration201Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = createFederationTeamValidateBeforeCall(teamId, createFederationTeamRequest, _callback);
        Type localVarReturnType = new TypeToken<CreateDarIntegration201Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deleteFederation
     * @param teamId team id (required)
     * @param federationId federation id (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Error response </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteFederationCall(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer federationId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/teams/{teamId}/federations/{federationId}"
            .replace("{" + "teamId" + "}", localVarApiClient.escapeString(teamId.toString()))
            .replace("{" + "federationId" + "}", localVarApiClient.escapeString(federationId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteFederationValidateBeforeCall(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer federationId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'teamId' is set
        if (teamId == null) {
            throw new ApiException("Missing the required parameter 'teamId' when calling deleteFederation(Async)");
        }

        // verify the required parameter 'federationId' is set
        if (federationId == null) {
            throw new ApiException("Missing the required parameter 'federationId' when calling deleteFederation(Async)");
        }

        return deleteFederationCall(teamId, federationId, _callback);

    }

    /**
     * FederationController@destroy
     * Delete federation for team
     * @param teamId team id (required)
     * @param federationId federation id (required)
     * @return DeleteFederation200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Error response </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public DeleteFederation200Response deleteFederation(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer federationId) throws ApiException {
        ApiResponse<DeleteFederation200Response> localVarResp = deleteFederationWithHttpInfo(teamId, federationId);
        return localVarResp.getData();
    }

    /**
     * FederationController@destroy
     * Delete federation for team
     * @param teamId team id (required)
     * @param federationId federation id (required)
     * @return ApiResponse&lt;DeleteFederation200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Error response </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<DeleteFederation200Response> deleteFederationWithHttpInfo(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer federationId) throws ApiException {
        okhttp3.Call localVarCall = deleteFederationValidateBeforeCall(teamId, federationId, null);
        Type localVarReturnType = new TypeToken<DeleteFederation200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * FederationController@destroy (asynchronously)
     * Delete federation for team
     * @param teamId team id (required)
     * @param federationId federation id (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Error response </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteFederationAsync(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer federationId, final ApiCallback<DeleteFederation200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteFederationValidateBeforeCall(teamId, federationId, _callback);
        Type localVarReturnType = new TypeToken<DeleteFederation200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getFederationByFederationIdAndTeamId
     * @param teamId team id (required)
     * @param federationId federation id (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getFederationByFederationIdAndTeamIdCall(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer federationId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/teams/{teamId}/federations/{federationId}"
            .replace("{" + "teamId" + "}", localVarApiClient.escapeString(teamId.toString()))
            .replace("{" + "federationId" + "}", localVarApiClient.escapeString(federationId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getFederationByFederationIdAndTeamIdValidateBeforeCall(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer federationId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'teamId' is set
        if (teamId == null) {
            throw new ApiException("Missing the required parameter 'teamId' when calling getFederationByFederationIdAndTeamId(Async)");
        }

        // verify the required parameter 'federationId' is set
        if (federationId == null) {
            throw new ApiException("Missing the required parameter 'federationId' when calling getFederationByFederationIdAndTeamId(Async)");
        }

        return getFederationByFederationIdAndTeamIdCall(teamId, federationId, _callback);

    }

    /**
     * FederationController@show
     * Get federation by federation id from team id
     * @param teamId team id (required)
     * @param federationId federation id (required)
     * @return GetFederationByFederationIdAndTeamId200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public GetFederationByFederationIdAndTeamId200Response getFederationByFederationIdAndTeamId(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer federationId) throws ApiException {
        ApiResponse<GetFederationByFederationIdAndTeamId200Response> localVarResp = getFederationByFederationIdAndTeamIdWithHttpInfo(teamId, federationId);
        return localVarResp.getData();
    }

    /**
     * FederationController@show
     * Get federation by federation id from team id
     * @param teamId team id (required)
     * @param federationId federation id (required)
     * @return ApiResponse&lt;GetFederationByFederationIdAndTeamId200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetFederationByFederationIdAndTeamId200Response> getFederationByFederationIdAndTeamIdWithHttpInfo(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer federationId) throws ApiException {
        okhttp3.Call localVarCall = getFederationByFederationIdAndTeamIdValidateBeforeCall(teamId, federationId, null);
        Type localVarReturnType = new TypeToken<GetFederationByFederationIdAndTeamId200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * FederationController@show (asynchronously)
     * Get federation by federation id from team id
     * @param teamId team id (required)
     * @param federationId federation id (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getFederationByFederationIdAndTeamIdAsync(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer federationId, final ApiCallback<GetFederationByFederationIdAndTeamId200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getFederationByFederationIdAndTeamIdValidateBeforeCall(teamId, federationId, _callback);
        Type localVarReturnType = new TypeToken<GetFederationByFederationIdAndTeamId200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getFederationHistory
     * @param teamId team id (required)
     * @param federationId federation id (required)
     * @param perPage per page (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getFederationHistoryCall(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer federationId, @javax.annotation.Nullable Integer perPage, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/teams/{teamId}/federations/{federationId}/history"
            .replace("{" + "teamId" + "}", localVarApiClient.escapeString(teamId.toString()))
            .replace("{" + "federationId" + "}", localVarApiClient.escapeString(federationId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (perPage != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("per_page", perPage));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getFederationHistoryValidateBeforeCall(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer federationId, @javax.annotation.Nullable Integer perPage, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'teamId' is set
        if (teamId == null) {
            throw new ApiException("Missing the required parameter 'teamId' when calling getFederationHistory(Async)");
        }

        // verify the required parameter 'federationId' is set
        if (federationId == null) {
            throw new ApiException("Missing the required parameter 'federationId' when calling getFederationHistory(Async)");
        }

        return getFederationHistoryCall(teamId, federationId, perPage, _callback);

    }

    /**
     * FederationController@history
     * Get run history for a federation
     * @param teamId team id (required)
     * @param federationId federation id (required)
     * @param perPage per page (optional)
     * @return GetFederationHistory200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
     </table>
     */
    public GetFederationHistory200Response getFederationHistory(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer federationId, @javax.annotation.Nullable Integer perPage) throws ApiException {
        ApiResponse<GetFederationHistory200Response> localVarResp = getFederationHistoryWithHttpInfo(teamId, federationId, perPage);
        return localVarResp.getData();
    }

    /**
     * FederationController@history
     * Get run history for a federation
     * @param teamId team id (required)
     * @param federationId federation id (required)
     * @param perPage per page (optional)
     * @return ApiResponse&lt;GetFederationHistory200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetFederationHistory200Response> getFederationHistoryWithHttpInfo(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer federationId, @javax.annotation.Nullable Integer perPage) throws ApiException {
        okhttp3.Call localVarCall = getFederationHistoryValidateBeforeCall(teamId, federationId, perPage, null);
        Type localVarReturnType = new TypeToken<GetFederationHistory200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * FederationController@history (asynchronously)
     * Get run history for a federation
     * @param teamId team id (required)
     * @param federationId federation id (required)
     * @param perPage per page (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getFederationHistoryAsync(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer federationId, @javax.annotation.Nullable Integer perPage, final ApiCallback<GetFederationHistory200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getFederationHistoryValidateBeforeCall(teamId, federationId, perPage, _callback);
        Type localVarReturnType = new TypeToken<GetFederationHistory200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getFederationTeamId
     * @param teamId team id (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getFederationTeamIdCall(@javax.annotation.Nonnull Integer teamId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/teams/{teamId}/federations"
            .replace("{" + "teamId" + "}", localVarApiClient.escapeString(teamId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getFederationTeamIdValidateBeforeCall(@javax.annotation.Nonnull Integer teamId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'teamId' is set
        if (teamId == null) {
            throw new ApiException("Missing the required parameter 'teamId' when calling getFederationTeamId(Async)");
        }

        return getFederationTeamIdCall(teamId, _callback);

    }

    /**
     * FederationController@index
     * Get federations by team id
     * @param teamId team id (required)
     * @return GetFederationTeamId200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
     </table>
     */
    public GetFederationTeamId200Response getFederationTeamId(@javax.annotation.Nonnull Integer teamId) throws ApiException {
        ApiResponse<GetFederationTeamId200Response> localVarResp = getFederationTeamIdWithHttpInfo(teamId);
        return localVarResp.getData();
    }

    /**
     * FederationController@index
     * Get federations by team id
     * @param teamId team id (required)
     * @return ApiResponse&lt;GetFederationTeamId200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetFederationTeamId200Response> getFederationTeamIdWithHttpInfo(@javax.annotation.Nonnull Integer teamId) throws ApiException {
        okhttp3.Call localVarCall = getFederationTeamIdValidateBeforeCall(teamId, null);
        Type localVarReturnType = new TypeToken<GetFederationTeamId200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * FederationController@index (asynchronously)
     * Get federations by team id
     * @param teamId team id (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getFederationTeamIdAsync(@javax.annotation.Nonnull Integer teamId, final ApiCallback<GetFederationTeamId200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getFederationTeamIdValidateBeforeCall(teamId, _callback);
        Type localVarReturnType = new TypeToken<GetFederationTeamId200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for runFederation
     * @param teamId team id (required)
     * @param federationId federation id (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call runFederationCall(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer federationId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/teams/{teamId}/federations/{federationId}/run"
            .replace("{" + "teamId" + "}", localVarApiClient.escapeString(teamId.toString()))
            .replace("{" + "federationId" + "}", localVarApiClient.escapeString(federationId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call runFederationValidateBeforeCall(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer federationId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'teamId' is set
        if (teamId == null) {
            throw new ApiException("Missing the required parameter 'teamId' when calling runFederation(Async)");
        }

        // verify the required parameter 'federationId' is set
        if (federationId == null) {
            throw new ApiException("Missing the required parameter 'federationId' when calling runFederation(Async)");
        }

        return runFederationCall(teamId, federationId, _callback);

    }

    /**
     * FederationController@runNow
     * Run federation immediately
     * @param teamId team id (required)
     * @param federationId federation id (required)
     * @return TestFederation200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
     </table>
     */
    public TestFederation200Response runFederation(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer federationId) throws ApiException {
        ApiResponse<TestFederation200Response> localVarResp = runFederationWithHttpInfo(teamId, federationId);
        return localVarResp.getData();
    }

    /**
     * FederationController@runNow
     * Run federation immediately
     * @param teamId team id (required)
     * @param federationId federation id (required)
     * @return ApiResponse&lt;TestFederation200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<TestFederation200Response> runFederationWithHttpInfo(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer federationId) throws ApiException {
        okhttp3.Call localVarCall = runFederationValidateBeforeCall(teamId, federationId, null);
        Type localVarReturnType = new TypeToken<TestFederation200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * FederationController@runNow (asynchronously)
     * Run federation immediately
     * @param teamId team id (required)
     * @param federationId federation id (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call runFederationAsync(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer federationId, final ApiCallback<TestFederation200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = runFederationValidateBeforeCall(teamId, federationId, _callback);
        Type localVarReturnType = new TypeToken<TestFederation200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for testFederation
     * @param teamId team id (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call testFederationCall(@javax.annotation.Nonnull Integer teamId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/teams/{teamId}/federations/test"
            .replace("{" + "teamId" + "}", localVarApiClient.escapeString(teamId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call testFederationValidateBeforeCall(@javax.annotation.Nonnull Integer teamId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'teamId' is set
        if (teamId == null) {
            throw new ApiException("Missing the required parameter 'teamId' when calling testFederation(Async)");
        }

        return testFederationCall(teamId, _callback);

    }

    /**
     * FederationController@testFederation
     * Test federation configuration
     * @param teamId team id (required)
     * @return TestFederation200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
     </table>
     */
    public TestFederation200Response testFederation(@javax.annotation.Nonnull Integer teamId) throws ApiException {
        ApiResponse<TestFederation200Response> localVarResp = testFederationWithHttpInfo(teamId);
        return localVarResp.getData();
    }

    /**
     * FederationController@testFederation
     * Test federation configuration
     * @param teamId team id (required)
     * @return ApiResponse&lt;TestFederation200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<TestFederation200Response> testFederationWithHttpInfo(@javax.annotation.Nonnull Integer teamId) throws ApiException {
        okhttp3.Call localVarCall = testFederationValidateBeforeCall(teamId, null);
        Type localVarReturnType = new TypeToken<TestFederation200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * FederationController@testFederation (asynchronously)
     * Test federation configuration
     * @param teamId team id (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call testFederationAsync(@javax.annotation.Nonnull Integer teamId, final ApiCallback<TestFederation200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = testFederationValidateBeforeCall(teamId, _callback);
        Type localVarReturnType = new TypeToken<TestFederation200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateFederationTeam
     * @param teamId team id (required)
     * @param federationId federation id (required)
     * @param updateFederationTeamRequest Pass user credentials (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Created </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateFederationTeamCall(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer federationId, @javax.annotation.Nonnull UpdateFederationTeamRequest updateFederationTeamRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = updateFederationTeamRequest;

        // create path and map variables
        String localVarPath = "/api/v1/teams/{teamId}/federations/{federationId}"
            .replace("{" + "teamId" + "}", localVarApiClient.escapeString(teamId.toString()))
            .replace("{" + "federationId" + "}", localVarApiClient.escapeString(federationId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateFederationTeamValidateBeforeCall(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer federationId, @javax.annotation.Nonnull UpdateFederationTeamRequest updateFederationTeamRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'teamId' is set
        if (teamId == null) {
            throw new ApiException("Missing the required parameter 'teamId' when calling updateFederationTeam(Async)");
        }

        // verify the required parameter 'federationId' is set
        if (federationId == null) {
            throw new ApiException("Missing the required parameter 'federationId' when calling updateFederationTeam(Async)");
        }

        // verify the required parameter 'updateFederationTeamRequest' is set
        if (updateFederationTeamRequest == null) {
            throw new ApiException("Missing the required parameter 'updateFederationTeamRequest' when calling updateFederationTeam(Async)");
        }

        return updateFederationTeamCall(teamId, federationId, updateFederationTeamRequest, _callback);

    }

    /**
     * FederationController@update
     * Update federation for team
     * @param teamId team id (required)
     * @param federationId federation id (required)
     * @param updateFederationTeamRequest Pass user credentials (required)
     * @return CreateDarIntegration201Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Created </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public CreateDarIntegration201Response updateFederationTeam(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer federationId, @javax.annotation.Nonnull UpdateFederationTeamRequest updateFederationTeamRequest) throws ApiException {
        ApiResponse<CreateDarIntegration201Response> localVarResp = updateFederationTeamWithHttpInfo(teamId, federationId, updateFederationTeamRequest);
        return localVarResp.getData();
    }

    /**
     * FederationController@update
     * Update federation for team
     * @param teamId team id (required)
     * @param federationId federation id (required)
     * @param updateFederationTeamRequest Pass user credentials (required)
     * @return ApiResponse&lt;CreateDarIntegration201Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Created </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CreateDarIntegration201Response> updateFederationTeamWithHttpInfo(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer federationId, @javax.annotation.Nonnull UpdateFederationTeamRequest updateFederationTeamRequest) throws ApiException {
        okhttp3.Call localVarCall = updateFederationTeamValidateBeforeCall(teamId, federationId, updateFederationTeamRequest, null);
        Type localVarReturnType = new TypeToken<CreateDarIntegration201Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * FederationController@update (asynchronously)
     * Update federation for team
     * @param teamId team id (required)
     * @param federationId federation id (required)
     * @param updateFederationTeamRequest Pass user credentials (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Created </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateFederationTeamAsync(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer federationId, @javax.annotation.Nonnull UpdateFederationTeamRequest updateFederationTeamRequest, final ApiCallback<CreateDarIntegration201Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateFederationTeamValidateBeforeCall(teamId, federationId, updateFederationTeamRequest, _callback);
        Type localVarReturnType = new TypeToken<CreateDarIntegration201Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
