/*
 * HDRUK Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.gatewayapi.api;

import uk.ac.hdruk.gatewayapi.ApiCallback;
import uk.ac.hdruk.gatewayapi.ApiClient;
import uk.ac.hdruk.gatewayapi.ApiException;
import uk.ac.hdruk.gatewayapi.ApiResponse;
import uk.ac.hdruk.gatewayapi.Configuration;
import uk.ac.hdruk.gatewayapi.Pair;
import uk.ac.hdruk.gatewayapi.ProgressRequestBody;
import uk.ac.hdruk.gatewayapi.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import uk.ac.hdruk.gatewayapi.model.CountUniqueFieldsCollections200Response;
import uk.ac.hdruk.gatewayapi.model.CreateAliases500Response;
import uk.ac.hdruk.gatewayapi.model.CreateTeamCollections401Response;
import uk.ac.hdruk.gatewayapi.model.DeleteAliases200Response;
import uk.ac.hdruk.gatewayapi.model.FetchDarTemplates200Response;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TeamDataAccessTemplateApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public TeamDataAccessTemplateApi() {
        this(Configuration.getDefaultApiClient());
    }

    public TeamDataAccessTemplateApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for deleteTeamDarTemplateFile
     * @param teamId Team id (required)
     * @param id DAR template id (required)
     * @param fileId File id (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteTeamDarTemplateFileCall(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull String fileId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/teams/{teamId}/dar/templates/{id}/files/{fileId}"
            .replace("{" + "teamId" + "}", localVarApiClient.escapeString(teamId.toString()))
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()))
            .replace("{" + "fileId" + "}", localVarApiClient.escapeString(fileId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteTeamDarTemplateFileValidateBeforeCall(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull String fileId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'teamId' is set
        if (teamId == null) {
            throw new ApiException("Missing the required parameter 'teamId' when calling deleteTeamDarTemplateFile(Async)");
        }

        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling deleteTeamDarTemplateFile(Async)");
        }

        // verify the required parameter 'fileId' is set
        if (fileId == null) {
            throw new ApiException("Missing the required parameter 'fileId' when calling deleteTeamDarTemplateFile(Async)");
        }

        return deleteTeamDarTemplateFileCall(teamId, id, fileId, _callback);

    }

    /**
     * TeamDataAccessTemplateController@destroyFile
     * Delete a file associated with a DAR template
     * @param teamId Team id (required)
     * @param id DAR template id (required)
     * @param fileId File id (required)
     * @return DeleteAliases200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public DeleteAliases200Response deleteTeamDarTemplateFile(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull String fileId) throws ApiException {
        ApiResponse<DeleteAliases200Response> localVarResp = deleteTeamDarTemplateFileWithHttpInfo(teamId, id, fileId);
        return localVarResp.getData();
    }

    /**
     * TeamDataAccessTemplateController@destroyFile
     * Delete a file associated with a DAR template
     * @param teamId Team id (required)
     * @param id DAR template id (required)
     * @param fileId File id (required)
     * @return ApiResponse&lt;DeleteAliases200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<DeleteAliases200Response> deleteTeamDarTemplateFileWithHttpInfo(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull String fileId) throws ApiException {
        okhttp3.Call localVarCall = deleteTeamDarTemplateFileValidateBeforeCall(teamId, id, fileId, null);
        Type localVarReturnType = new TypeToken<DeleteAliases200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * TeamDataAccessTemplateController@destroyFile (asynchronously)
     * Delete a file associated with a DAR template
     * @param teamId Team id (required)
     * @param id DAR template id (required)
     * @param fileId File id (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteTeamDarTemplateFileAsync(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull String fileId, final ApiCallback<DeleteAliases200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteTeamDarTemplateFileValidateBeforeCall(teamId, id, fileId, _callback);
        Type localVarReturnType = new TypeToken<DeleteAliases200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for fetchTeamDarTemplates
     * @param teamId Team id (required)
     * @param published Template publication status to filter by (true, false) (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call fetchTeamDarTemplatesCall(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nullable String published, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/teams/{teamId}/dar/templates"
            .replace("{" + "teamId" + "}", localVarApiClient.escapeString(teamId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (published != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("published", published));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call fetchTeamDarTemplatesValidateBeforeCall(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nullable String published, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'teamId' is set
        if (teamId == null) {
            throw new ApiException("Missing the required parameter 'teamId' when calling fetchTeamDarTemplates(Async)");
        }

        return fetchTeamDarTemplatesCall(teamId, published, _callback);

    }

    /**
     * TeamDataAccessTemplateController@index
     * List of dar templates belonging to a team
     * @param teamId Team id (required)
     * @param published Template publication status to filter by (true, false) (optional)
     * @return FetchDarTemplates200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public FetchDarTemplates200Response fetchTeamDarTemplates(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nullable String published) throws ApiException {
        ApiResponse<FetchDarTemplates200Response> localVarResp = fetchTeamDarTemplatesWithHttpInfo(teamId, published);
        return localVarResp.getData();
    }

    /**
     * TeamDataAccessTemplateController@index
     * List of dar templates belonging to a team
     * @param teamId Team id (required)
     * @param published Template publication status to filter by (true, false) (optional)
     * @return ApiResponse&lt;FetchDarTemplates200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<FetchDarTemplates200Response> fetchTeamDarTemplatesWithHttpInfo(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nullable String published) throws ApiException {
        okhttp3.Call localVarCall = fetchTeamDarTemplatesValidateBeforeCall(teamId, published, null);
        Type localVarReturnType = new TypeToken<FetchDarTemplates200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * TeamDataAccessTemplateController@index (asynchronously)
     * List of dar templates belonging to a team
     * @param teamId Team id (required)
     * @param published Template publication status to filter by (true, false) (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call fetchTeamDarTemplatesAsync(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nullable String published, final ApiCallback<FetchDarTemplates200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = fetchTeamDarTemplatesValidateBeforeCall(teamId, published, _callback);
        Type localVarReturnType = new TypeToken<FetchDarTemplates200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for teamDarTemplateCountUniqueFields
     * @param teamId Team id (required)
     * @param field name of the field to perform a count on (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call teamDarTemplateCountUniqueFieldsCall(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull String field, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/teams/{teamId}/dar/templates/count/{field}"
            .replace("{" + "teamId" + "}", localVarApiClient.escapeString(teamId.toString()))
            .replace("{" + "field" + "}", localVarApiClient.escapeString(field.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call teamDarTemplateCountUniqueFieldsValidateBeforeCall(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull String field, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'teamId' is set
        if (teamId == null) {
            throw new ApiException("Missing the required parameter 'teamId' when calling teamDarTemplateCountUniqueFields(Async)");
        }

        // verify the required parameter 'field' is set
        if (field == null) {
            throw new ApiException("Missing the required parameter 'field' when calling teamDarTemplateCountUniqueFields(Async)");
        }

        return teamDarTemplateCountUniqueFieldsCall(teamId, field, _callback);

    }

    /**
     * TeamDataAccessTemplateController@count
     * Get Counts for distinct entries of a field in the model
     * @param teamId Team id (required)
     * @param field name of the field to perform a count on (required)
     * @return CountUniqueFieldsCollections200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
     </table>
     */
    public CountUniqueFieldsCollections200Response teamDarTemplateCountUniqueFields(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull String field) throws ApiException {
        ApiResponse<CountUniqueFieldsCollections200Response> localVarResp = teamDarTemplateCountUniqueFieldsWithHttpInfo(teamId, field);
        return localVarResp.getData();
    }

    /**
     * TeamDataAccessTemplateController@count
     * Get Counts for distinct entries of a field in the model
     * @param teamId Team id (required)
     * @param field name of the field to perform a count on (required)
     * @return ApiResponse&lt;CountUniqueFieldsCollections200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CountUniqueFieldsCollections200Response> teamDarTemplateCountUniqueFieldsWithHttpInfo(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull String field) throws ApiException {
        okhttp3.Call localVarCall = teamDarTemplateCountUniqueFieldsValidateBeforeCall(teamId, field, null);
        Type localVarReturnType = new TypeToken<CountUniqueFieldsCollections200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * TeamDataAccessTemplateController@count (asynchronously)
     * Get Counts for distinct entries of a field in the model
     * @param teamId Team id (required)
     * @param field name of the field to perform a count on (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call teamDarTemplateCountUniqueFieldsAsync(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull String field, final ApiCallback<CountUniqueFieldsCollections200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = teamDarTemplateCountUniqueFieldsValidateBeforeCall(teamId, field, _callback);
        Type localVarReturnType = new TypeToken<CountUniqueFieldsCollections200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
