/*
 * HDRUK Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.gatewayapi.api;

import uk.ac.hdruk.gatewayapi.ApiCallback;
import uk.ac.hdruk.gatewayapi.ApiClient;
import uk.ac.hdruk.gatewayapi.ApiException;
import uk.ac.hdruk.gatewayapi.ApiResponse;
import uk.ac.hdruk.gatewayapi.Configuration;
import uk.ac.hdruk.gatewayapi.Pair;
import uk.ac.hdruk.gatewayapi.ProgressRequestBody;
import uk.ac.hdruk.gatewayapi.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import uk.ac.hdruk.gatewayapi.model.CountUniqueFieldsCollections200Response;
import uk.ac.hdruk.gatewayapi.model.CreateAliases500Response;
import uk.ac.hdruk.gatewayapi.model.CreateCategories200Response;
import uk.ac.hdruk.gatewayapi.model.CreateUserDarApplicationAnswersRequest;
import uk.ac.hdruk.gatewayapi.model.FetchAliases404Response;
import uk.ac.hdruk.gatewayapi.model.FetchTeamDarApplication200Response;
import uk.ac.hdruk.gatewayapi.model.FetchTeamDarApplicationAnswers200Response;
import uk.ac.hdruk.gatewayapi.model.FetchTeamDarApplications200Response;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class UserDataAccessApplicationApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public UserDataAccessApplicationApi() {
        this(Configuration.getDefaultApiClient());
    }

    public UserDataAccessApplicationApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for countAllUserDarApplications
     * @param userId User id (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call countAllUserDarApplicationsCall(@javax.annotation.Nonnull Integer userId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/users/{userId}/dar/applications/count"
            .replace("{" + "userId" + "}", localVarApiClient.escapeString(userId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call countAllUserDarApplicationsValidateBeforeCall(@javax.annotation.Nonnull Integer userId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'userId' is set
        if (userId == null) {
            throw new ApiException("Missing the required parameter 'userId' when calling countAllUserDarApplications(Async)");
        }

        return countAllUserDarApplicationsCall(userId, _callback);

    }

    /**
     * UserDataAccessApplicationController@allCounts
     * Get Counts for all status fields in the model
     * @param userId User id (required)
     * @return CountUniqueFieldsCollections200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
     </table>
     */
    public CountUniqueFieldsCollections200Response countAllUserDarApplications(@javax.annotation.Nonnull Integer userId) throws ApiException {
        ApiResponse<CountUniqueFieldsCollections200Response> localVarResp = countAllUserDarApplicationsWithHttpInfo(userId);
        return localVarResp.getData();
    }

    /**
     * UserDataAccessApplicationController@allCounts
     * Get Counts for all status fields in the model
     * @param userId User id (required)
     * @return ApiResponse&lt;CountUniqueFieldsCollections200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CountUniqueFieldsCollections200Response> countAllUserDarApplicationsWithHttpInfo(@javax.annotation.Nonnull Integer userId) throws ApiException {
        okhttp3.Call localVarCall = countAllUserDarApplicationsValidateBeforeCall(userId, null);
        Type localVarReturnType = new TypeToken<CountUniqueFieldsCollections200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * UserDataAccessApplicationController@allCounts (asynchronously)
     * Get Counts for all status fields in the model
     * @param userId User id (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call countAllUserDarApplicationsAsync(@javax.annotation.Nonnull Integer userId, final ApiCallback<CountUniqueFieldsCollections200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = countAllUserDarApplicationsValidateBeforeCall(userId, _callback);
        Type localVarReturnType = new TypeToken<CountUniqueFieldsCollections200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for countUserDarApplicationsByField
     * @param userId User id (required)
     * @param field name of the field to perform a count on (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call countUserDarApplicationsByFieldCall(@javax.annotation.Nonnull Integer userId, @javax.annotation.Nonnull String field, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/users/{userId}/dar/applications/count/{field}"
            .replace("{" + "userId" + "}", localVarApiClient.escapeString(userId.toString()))
            .replace("{" + "field" + "}", localVarApiClient.escapeString(field.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call countUserDarApplicationsByFieldValidateBeforeCall(@javax.annotation.Nonnull Integer userId, @javax.annotation.Nonnull String field, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'userId' is set
        if (userId == null) {
            throw new ApiException("Missing the required parameter 'userId' when calling countUserDarApplicationsByField(Async)");
        }

        // verify the required parameter 'field' is set
        if (field == null) {
            throw new ApiException("Missing the required parameter 'field' when calling countUserDarApplicationsByField(Async)");
        }

        return countUserDarApplicationsByFieldCall(userId, field, _callback);

    }

    /**
     * UserDataAccessApplicationController@count
     * Get Counts for distinct entries of a field in the model
     * @param userId User id (required)
     * @param field name of the field to perform a count on (required)
     * @return CountUniqueFieldsCollections200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
     </table>
     */
    public CountUniqueFieldsCollections200Response countUserDarApplicationsByField(@javax.annotation.Nonnull Integer userId, @javax.annotation.Nonnull String field) throws ApiException {
        ApiResponse<CountUniqueFieldsCollections200Response> localVarResp = countUserDarApplicationsByFieldWithHttpInfo(userId, field);
        return localVarResp.getData();
    }

    /**
     * UserDataAccessApplicationController@count
     * Get Counts for distinct entries of a field in the model
     * @param userId User id (required)
     * @param field name of the field to perform a count on (required)
     * @return ApiResponse&lt;CountUniqueFieldsCollections200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CountUniqueFieldsCollections200Response> countUserDarApplicationsByFieldWithHttpInfo(@javax.annotation.Nonnull Integer userId, @javax.annotation.Nonnull String field) throws ApiException {
        okhttp3.Call localVarCall = countUserDarApplicationsByFieldValidateBeforeCall(userId, field, null);
        Type localVarReturnType = new TypeToken<CountUniqueFieldsCollections200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * UserDataAccessApplicationController@count (asynchronously)
     * Get Counts for distinct entries of a field in the model
     * @param userId User id (required)
     * @param field name of the field to perform a count on (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call countUserDarApplicationsByFieldAsync(@javax.annotation.Nonnull Integer userId, @javax.annotation.Nonnull String field, final ApiCallback<CountUniqueFieldsCollections200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = countUserDarApplicationsByFieldValidateBeforeCall(userId, field, _callback);
        Type localVarReturnType = new TypeToken<CountUniqueFieldsCollections200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for createUserDarApplicationAnswers
     * @param userId User id (required)
     * @param id DAR application id (required)
     * @param createUserDarApplicationAnswersRequest UserDataAccessApplication definition (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createUserDarApplicationAnswersCall(@javax.annotation.Nonnull Integer userId, @javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull CreateUserDarApplicationAnswersRequest createUserDarApplicationAnswersRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createUserDarApplicationAnswersRequest;

        // create path and map variables
        String localVarPath = "/api/v1/users/{userId}/dar/applications/{id}/answers"
            .replace("{" + "userId" + "}", localVarApiClient.escapeString(userId.toString()))
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createUserDarApplicationAnswersValidateBeforeCall(@javax.annotation.Nonnull Integer userId, @javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull CreateUserDarApplicationAnswersRequest createUserDarApplicationAnswersRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'userId' is set
        if (userId == null) {
            throw new ApiException("Missing the required parameter 'userId' when calling createUserDarApplicationAnswers(Async)");
        }

        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling createUserDarApplicationAnswers(Async)");
        }

        // verify the required parameter 'createUserDarApplicationAnswersRequest' is set
        if (createUserDarApplicationAnswersRequest == null) {
            throw new ApiException("Missing the required parameter 'createUserDarApplicationAnswersRequest' when calling createUserDarApplicationAnswers(Async)");
        }

        return createUserDarApplicationAnswersCall(userId, id, createUserDarApplicationAnswersRequest, _callback);

    }

    /**
     * UserDataAccessApplication@storeAnswers
     * Add answers to the user&#39;s DAR application
     * @param userId User id (required)
     * @param id DAR application id (required)
     * @param createUserDarApplicationAnswersRequest UserDataAccessApplication definition (required)
     * @return CreateCategories200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public CreateCategories200Response createUserDarApplicationAnswers(@javax.annotation.Nonnull Integer userId, @javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull CreateUserDarApplicationAnswersRequest createUserDarApplicationAnswersRequest) throws ApiException {
        ApiResponse<CreateCategories200Response> localVarResp = createUserDarApplicationAnswersWithHttpInfo(userId, id, createUserDarApplicationAnswersRequest);
        return localVarResp.getData();
    }

    /**
     * UserDataAccessApplication@storeAnswers
     * Add answers to the user&#39;s DAR application
     * @param userId User id (required)
     * @param id DAR application id (required)
     * @param createUserDarApplicationAnswersRequest UserDataAccessApplication definition (required)
     * @return ApiResponse&lt;CreateCategories200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CreateCategories200Response> createUserDarApplicationAnswersWithHttpInfo(@javax.annotation.Nonnull Integer userId, @javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull CreateUserDarApplicationAnswersRequest createUserDarApplicationAnswersRequest) throws ApiException {
        okhttp3.Call localVarCall = createUserDarApplicationAnswersValidateBeforeCall(userId, id, createUserDarApplicationAnswersRequest, null);
        Type localVarReturnType = new TypeToken<CreateCategories200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * UserDataAccessApplication@storeAnswers (asynchronously)
     * Add answers to the user&#39;s DAR application
     * @param userId User id (required)
     * @param id DAR application id (required)
     * @param createUserDarApplicationAnswersRequest UserDataAccessApplication definition (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createUserDarApplicationAnswersAsync(@javax.annotation.Nonnull Integer userId, @javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull CreateUserDarApplicationAnswersRequest createUserDarApplicationAnswersRequest, final ApiCallback<CreateCategories200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = createUserDarApplicationAnswersValidateBeforeCall(userId, id, createUserDarApplicationAnswersRequest, _callback);
        Type localVarReturnType = new TypeToken<CreateCategories200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for fetchUserDarApplicationAnswers
     * @param userId User id (required)
     * @param id DAR application id (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call fetchUserDarApplicationAnswersCall(@javax.annotation.Nonnull Integer userId, @javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/users/{userId}/dar/applications/{id}/answers"
            .replace("{" + "userId" + "}", localVarApiClient.escapeString(userId.toString()))
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call fetchUserDarApplicationAnswersValidateBeforeCall(@javax.annotation.Nonnull Integer userId, @javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'userId' is set
        if (userId == null) {
            throw new ApiException("Missing the required parameter 'userId' when calling fetchUserDarApplicationAnswers(Async)");
        }

        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling fetchUserDarApplicationAnswers(Async)");
        }

        return fetchUserDarApplicationAnswersCall(userId, id, _callback);

    }

    /**
     * UserDataAccessApplicationController@showAnswers
     * Return answers from the user&#39;s DAR application
     * @param userId User id (required)
     * @param id DAR application id (required)
     * @return FetchTeamDarApplicationAnswers200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
     </table>
     */
    public FetchTeamDarApplicationAnswers200Response fetchUserDarApplicationAnswers(@javax.annotation.Nonnull Integer userId, @javax.annotation.Nonnull Integer id) throws ApiException {
        ApiResponse<FetchTeamDarApplicationAnswers200Response> localVarResp = fetchUserDarApplicationAnswersWithHttpInfo(userId, id);
        return localVarResp.getData();
    }

    /**
     * UserDataAccessApplicationController@showAnswers
     * Return answers from the user&#39;s DAR application
     * @param userId User id (required)
     * @param id DAR application id (required)
     * @return ApiResponse&lt;FetchTeamDarApplicationAnswers200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<FetchTeamDarApplicationAnswers200Response> fetchUserDarApplicationAnswersWithHttpInfo(@javax.annotation.Nonnull Integer userId, @javax.annotation.Nonnull Integer id) throws ApiException {
        okhttp3.Call localVarCall = fetchUserDarApplicationAnswersValidateBeforeCall(userId, id, null);
        Type localVarReturnType = new TypeToken<FetchTeamDarApplicationAnswers200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * UserDataAccessApplicationController@showAnswers (asynchronously)
     * Return answers from the user&#39;s DAR application
     * @param userId User id (required)
     * @param id DAR application id (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call fetchUserDarApplicationAnswersAsync(@javax.annotation.Nonnull Integer userId, @javax.annotation.Nonnull Integer id, final ApiCallback<FetchTeamDarApplicationAnswers200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = fetchUserDarApplicationAnswersValidateBeforeCall(userId, id, _callback);
        Type localVarReturnType = new TypeToken<FetchTeamDarApplicationAnswers200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for fetchUserDarApplicationDetails
     * @param userId User id (required)
     * @param id DAR application id (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call fetchUserDarApplicationDetailsCall(@javax.annotation.Nonnull Integer userId, @javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/users/{userId}/dar/applications/{id}"
            .replace("{" + "userId" + "}", localVarApiClient.escapeString(userId.toString()))
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call fetchUserDarApplicationDetailsValidateBeforeCall(@javax.annotation.Nonnull Integer userId, @javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'userId' is set
        if (userId == null) {
            throw new ApiException("Missing the required parameter 'userId' when calling fetchUserDarApplicationDetails(Async)");
        }

        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling fetchUserDarApplicationDetails(Async)");
        }

        return fetchUserDarApplicationDetailsCall(userId, id, _callback);

    }

    /**
     * UserDataAccessApplicationController@show
     * Return a DAR application belonging to the user
     * @param userId User id (required)
     * @param id DAR application id (required)
     * @return FetchTeamDarApplication200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
     </table>
     */
    public FetchTeamDarApplication200Response fetchUserDarApplicationDetails(@javax.annotation.Nonnull Integer userId, @javax.annotation.Nonnull Integer id) throws ApiException {
        ApiResponse<FetchTeamDarApplication200Response> localVarResp = fetchUserDarApplicationDetailsWithHttpInfo(userId, id);
        return localVarResp.getData();
    }

    /**
     * UserDataAccessApplicationController@show
     * Return a DAR application belonging to the user
     * @param userId User id (required)
     * @param id DAR application id (required)
     * @return ApiResponse&lt;FetchTeamDarApplication200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<FetchTeamDarApplication200Response> fetchUserDarApplicationDetailsWithHttpInfo(@javax.annotation.Nonnull Integer userId, @javax.annotation.Nonnull Integer id) throws ApiException {
        okhttp3.Call localVarCall = fetchUserDarApplicationDetailsValidateBeforeCall(userId, id, null);
        Type localVarReturnType = new TypeToken<FetchTeamDarApplication200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * UserDataAccessApplicationController@show (asynchronously)
     * Return a DAR application belonging to the user
     * @param userId User id (required)
     * @param id DAR application id (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call fetchUserDarApplicationDetailsAsync(@javax.annotation.Nonnull Integer userId, @javax.annotation.Nonnull Integer id, final ApiCallback<FetchTeamDarApplication200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = fetchUserDarApplicationDetailsValidateBeforeCall(userId, id, _callback);
        Type localVarReturnType = new TypeToken<FetchTeamDarApplication200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for fetchUserDarApplicationHeader
     * @param userId User id (required)
     * @param id DAR application id (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call fetchUserDarApplicationHeaderCall(@javax.annotation.Nonnull Integer userId, @javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/users/{userId}/dar/applications/{id}/showHeader"
            .replace("{" + "userId" + "}", localVarApiClient.escapeString(userId.toString()))
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call fetchUserDarApplicationHeaderValidateBeforeCall(@javax.annotation.Nonnull Integer userId, @javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'userId' is set
        if (userId == null) {
            throw new ApiException("Missing the required parameter 'userId' when calling fetchUserDarApplicationHeader(Async)");
        }

        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling fetchUserDarApplicationHeader(Async)");
        }

        return fetchUserDarApplicationHeaderCall(userId, id, _callback);

    }

    /**
     * UserDataAccessApplicationController@showHeader
     * Get header information about a specific DAR
     * @param userId User id (required)
     * @param id DAR application id (required)
     * @return FetchTeamDarApplication200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public FetchTeamDarApplication200Response fetchUserDarApplicationHeader(@javax.annotation.Nonnull Integer userId, @javax.annotation.Nonnull Integer id) throws ApiException {
        ApiResponse<FetchTeamDarApplication200Response> localVarResp = fetchUserDarApplicationHeaderWithHttpInfo(userId, id);
        return localVarResp.getData();
    }

    /**
     * UserDataAccessApplicationController@showHeader
     * Get header information about a specific DAR
     * @param userId User id (required)
     * @param id DAR application id (required)
     * @return ApiResponse&lt;FetchTeamDarApplication200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<FetchTeamDarApplication200Response> fetchUserDarApplicationHeaderWithHttpInfo(@javax.annotation.Nonnull Integer userId, @javax.annotation.Nonnull Integer id) throws ApiException {
        okhttp3.Call localVarCall = fetchUserDarApplicationHeaderValidateBeforeCall(userId, id, null);
        Type localVarReturnType = new TypeToken<FetchTeamDarApplication200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * UserDataAccessApplicationController@showHeader (asynchronously)
     * Get header information about a specific DAR
     * @param userId User id (required)
     * @param id DAR application id (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call fetchUserDarApplicationHeaderAsync(@javax.annotation.Nonnull Integer userId, @javax.annotation.Nonnull Integer id, final ApiCallback<FetchTeamDarApplication200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = fetchUserDarApplicationHeaderValidateBeforeCall(userId, id, _callback);
        Type localVarReturnType = new TypeToken<FetchTeamDarApplication200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for fetchUserDarApplications
     * @param userId User id (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call fetchUserDarApplicationsCall(@javax.annotation.Nonnull Integer userId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/users/{userId}/dar/applications"
            .replace("{" + "userId" + "}", localVarApiClient.escapeString(userId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call fetchUserDarApplicationsValidateBeforeCall(@javax.annotation.Nonnull Integer userId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'userId' is set
        if (userId == null) {
            throw new ApiException("Missing the required parameter 'userId' when calling fetchUserDarApplications(Async)");
        }

        return fetchUserDarApplicationsCall(userId, _callback);

    }

    /**
     * UserDataAccessApplicationController@index
     * List of dar applications belonging to a user
     * @param userId User id (required)
     * @return FetchTeamDarApplications200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public FetchTeamDarApplications200Response fetchUserDarApplications(@javax.annotation.Nonnull Integer userId) throws ApiException {
        ApiResponse<FetchTeamDarApplications200Response> localVarResp = fetchUserDarApplicationsWithHttpInfo(userId);
        return localVarResp.getData();
    }

    /**
     * UserDataAccessApplicationController@index
     * List of dar applications belonging to a user
     * @param userId User id (required)
     * @return ApiResponse&lt;FetchTeamDarApplications200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<FetchTeamDarApplications200Response> fetchUserDarApplicationsWithHttpInfo(@javax.annotation.Nonnull Integer userId) throws ApiException {
        okhttp3.Call localVarCall = fetchUserDarApplicationsValidateBeforeCall(userId, null);
        Type localVarReturnType = new TypeToken<FetchTeamDarApplications200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * UserDataAccessApplicationController@index (asynchronously)
     * List of dar applications belonging to a user
     * @param userId User id (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call fetchUserDarApplicationsAsync(@javax.annotation.Nonnull Integer userId, final ApiCallback<FetchTeamDarApplications200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = fetchUserDarApplicationsValidateBeforeCall(userId, _callback);
        Type localVarReturnType = new TypeToken<FetchTeamDarApplications200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
