/*
 * HDRUK Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.gatewayapi.api;

import uk.ac.hdruk.gatewayapi.ApiCallback;
import uk.ac.hdruk.gatewayapi.ApiClient;
import uk.ac.hdruk.gatewayapi.ApiException;
import uk.ac.hdruk.gatewayapi.ApiResponse;
import uk.ac.hdruk.gatewayapi.Configuration;
import uk.ac.hdruk.gatewayapi.Pair;
import uk.ac.hdruk.gatewayapi.ProgressRequestBody;
import uk.ac.hdruk.gatewayapi.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import uk.ac.hdruk.gatewayapi.model.CreateApplications500Response;
import uk.ac.hdruk.gatewayapi.model.CreateDarIntegration201Response;
import uk.ac.hdruk.gatewayapi.model.CreateToolsIntegrations400Response;
import uk.ac.hdruk.gatewayapi.model.CreateUsersRequest;
import uk.ac.hdruk.gatewayapi.model.DeleteFederation200Response;
import uk.ac.hdruk.gatewayapi.model.DeleteFederation404Response;
import uk.ac.hdruk.gatewayapi.model.EditUsers200Response;
import uk.ac.hdruk.gatewayapi.model.EditUsersRequest;
import uk.ac.hdruk.gatewayapi.model.FetchAllDarIntegrations401Response;
import uk.ac.hdruk.gatewayapi.model.VerifySecondaryEmail200Response;
import uk.ac.hdruk.gatewayapi.model.VerifySecondaryEmail400Response;
import uk.ac.hdruk.gatewayapi.model.VerifySecondaryEmail404Response;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class UsersApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public UsersApi() {
        this(Configuration.getDefaultApiClient());
    }

    public UsersApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for createUsers
     * @param createUsersRequest Pass user credentials (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Created </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createUsersCall(@javax.annotation.Nonnull CreateUsersRequest createUsersRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createUsersRequest;

        // create path and map variables
        String localVarPath = "/api/v1/users";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createUsersValidateBeforeCall(@javax.annotation.Nonnull CreateUsersRequest createUsersRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'createUsersRequest' is set
        if (createUsersRequest == null) {
            throw new ApiException("Missing the required parameter 'createUsersRequest' when calling createUsers(Async)");
        }

        return createUsersCall(createUsersRequest, _callback);

    }

    /**
     * UserController@store
     * Create a new user
     * @param createUsersRequest Pass user credentials (required)
     * @return CreateDarIntegration201Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Created </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public CreateDarIntegration201Response createUsers(@javax.annotation.Nonnull CreateUsersRequest createUsersRequest) throws ApiException {
        ApiResponse<CreateDarIntegration201Response> localVarResp = createUsersWithHttpInfo(createUsersRequest);
        return localVarResp.getData();
    }

    /**
     * UserController@store
     * Create a new user
     * @param createUsersRequest Pass user credentials (required)
     * @return ApiResponse&lt;CreateDarIntegration201Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Created </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CreateDarIntegration201Response> createUsersWithHttpInfo(@javax.annotation.Nonnull CreateUsersRequest createUsersRequest) throws ApiException {
        okhttp3.Call localVarCall = createUsersValidateBeforeCall(createUsersRequest, null);
        Type localVarReturnType = new TypeToken<CreateDarIntegration201Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * UserController@store (asynchronously)
     * Create a new user
     * @param createUsersRequest Pass user credentials (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Created </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createUsersAsync(@javax.annotation.Nonnull CreateUsersRequest createUsersRequest, final ApiCallback<CreateDarIntegration201Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = createUsersValidateBeforeCall(createUsersRequest, _callback);
        Type localVarReturnType = new TypeToken<CreateDarIntegration201Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deleteUsers
     * @param id user id (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Error response </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteUsersCall(@javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/users/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteUsersValidateBeforeCall(@javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling deleteUsers(Async)");
        }

        return deleteUsersCall(id, _callback);

    }

    /**
     * UserController@destroy
     * Delete User based in id
     * @param id user id (required)
     * @return DeleteFederation200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Error response </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public DeleteFederation200Response deleteUsers(@javax.annotation.Nonnull Integer id) throws ApiException {
        ApiResponse<DeleteFederation200Response> localVarResp = deleteUsersWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * UserController@destroy
     * Delete User based in id
     * @param id user id (required)
     * @return ApiResponse&lt;DeleteFederation200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Error response </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<DeleteFederation200Response> deleteUsersWithHttpInfo(@javax.annotation.Nonnull Integer id) throws ApiException {
        okhttp3.Call localVarCall = deleteUsersValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<DeleteFederation200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * UserController@destroy (asynchronously)
     * Delete User based in id
     * @param id user id (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Error response </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteUsersAsync(@javax.annotation.Nonnull Integer id, final ApiCallback<DeleteFederation200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteUsersValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<DeleteFederation200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for editUsers
     * @param id user id (required)
     * @param editUsersRequest Pass user credentials (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Error </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Error response </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call editUsersCall(@javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull EditUsersRequest editUsersRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = editUsersRequest;

        // create path and map variables
        String localVarPath = "/api/v1/users/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call editUsersValidateBeforeCall(@javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull EditUsersRequest editUsersRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling editUsers(Async)");
        }

        // verify the required parameter 'editUsersRequest' is set
        if (editUsersRequest == null) {
            throw new ApiException("Missing the required parameter 'editUsersRequest' when calling editUsers(Async)");
        }

        return editUsersCall(id, editUsersRequest, _callback);

    }

    /**
     * UserController@edit
     * Edit user
     * @param id user id (required)
     * @param editUsersRequest Pass user credentials (required)
     * @return EditUsers200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Error </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Error response </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public EditUsers200Response editUsers(@javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull EditUsersRequest editUsersRequest) throws ApiException {
        ApiResponse<EditUsers200Response> localVarResp = editUsersWithHttpInfo(id, editUsersRequest);
        return localVarResp.getData();
    }

    /**
     * UserController@edit
     * Edit user
     * @param id user id (required)
     * @param editUsersRequest Pass user credentials (required)
     * @return ApiResponse&lt;EditUsers200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Error </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Error response </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<EditUsers200Response> editUsersWithHttpInfo(@javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull EditUsersRequest editUsersRequest) throws ApiException {
        okhttp3.Call localVarCall = editUsersValidateBeforeCall(id, editUsersRequest, null);
        Type localVarReturnType = new TypeToken<EditUsers200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * UserController@edit (asynchronously)
     * Edit user
     * @param id user id (required)
     * @param editUsersRequest Pass user credentials (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Error </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Error response </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call editUsersAsync(@javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull EditUsersRequest editUsersRequest, final ApiCallback<EditUsers200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = editUsersValidateBeforeCall(id, editUsersRequest, _callback);
        Type localVarReturnType = new TypeToken<EditUsers200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for verifySecondaryEmail
     * @param uuid Verification UUID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Email verified successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid or expired token </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> UUID not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call verifySecondaryEmailCall(@javax.annotation.Nonnull String uuid, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/users/verify-secondary-email/{uuid}"
            .replace("{" + "uuid" + "}", localVarApiClient.escapeString(uuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call verifySecondaryEmailValidateBeforeCall(@javax.annotation.Nonnull String uuid, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'uuid' is set
        if (uuid == null) {
            throw new ApiException("Missing the required parameter 'uuid' when calling verifySecondaryEmail(Async)");
        }

        return verifySecondaryEmailCall(uuid, _callback);

    }

    /**
     * Verify user&#39;s secondary email using a UUID
     * This endpoint verifies the secondary email for a user if the UUID is valid and not expired.
     * @param uuid Verification UUID (required)
     * @return VerifySecondaryEmail200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Email verified successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid or expired token </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> UUID not found </td><td>  -  </td></tr>
     </table>
     */
    public VerifySecondaryEmail200Response verifySecondaryEmail(@javax.annotation.Nonnull String uuid) throws ApiException {
        ApiResponse<VerifySecondaryEmail200Response> localVarResp = verifySecondaryEmailWithHttpInfo(uuid);
        return localVarResp.getData();
    }

    /**
     * Verify user&#39;s secondary email using a UUID
     * This endpoint verifies the secondary email for a user if the UUID is valid and not expired.
     * @param uuid Verification UUID (required)
     * @return ApiResponse&lt;VerifySecondaryEmail200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Email verified successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid or expired token </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> UUID not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<VerifySecondaryEmail200Response> verifySecondaryEmailWithHttpInfo(@javax.annotation.Nonnull String uuid) throws ApiException {
        okhttp3.Call localVarCall = verifySecondaryEmailValidateBeforeCall(uuid, null);
        Type localVarReturnType = new TypeToken<VerifySecondaryEmail200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Verify user&#39;s secondary email using a UUID (asynchronously)
     * This endpoint verifies the secondary email for a user if the UUID is valid and not expired.
     * @param uuid Verification UUID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Email verified successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid or expired token </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> UUID not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call verifySecondaryEmailAsync(@javax.annotation.Nonnull String uuid, final ApiCallback<VerifySecondaryEmail200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = verifySecondaryEmailValidateBeforeCall(uuid, _callback);
        Type localVarReturnType = new TypeToken<VerifySecondaryEmail200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
