/*
 * HDRUK Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.gatewayapi.api;

import uk.ac.hdruk.gatewayapi.ApiCallback;
import uk.ac.hdruk.gatewayapi.ApiClient;
import uk.ac.hdruk.gatewayapi.ApiException;
import uk.ac.hdruk.gatewayapi.ApiResponse;
import uk.ac.hdruk.gatewayapi.Configuration;
import uk.ac.hdruk.gatewayapi.Pair;
import uk.ac.hdruk.gatewayapi.ProgressRequestBody;
import uk.ac.hdruk.gatewayapi.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import uk.ac.hdruk.gatewayapi.model.CreateApplications500Response;
import uk.ac.hdruk.gatewayapi.model.CreateWidget201Response;
import uk.ac.hdruk.gatewayapi.model.CreateWidget400Response;
import uk.ac.hdruk.gatewayapi.model.CreateWidgetRequest;
import uk.ac.hdruk.gatewayapi.model.DeleteApplications200Response;
import uk.ac.hdruk.gatewayapi.model.FetchAllWidgets200Response;
import uk.ac.hdruk.gatewayapi.model.FetchWidget200Response;
import uk.ac.hdruk.gatewayapi.model.FetchWidgetDataSources200Response;
import uk.ac.hdruk.gatewayapi.model.FetchWidgetDataSources400Response;
import uk.ac.hdruk.gatewayapi.model.RetrieveWidgetData200Response;
import uk.ac.hdruk.gatewayapi.model.RetrieveWidgetData403Response;
import uk.ac.hdruk.gatewayapi.model.TrackWidgetEventRequest;
import uk.ac.hdruk.gatewayapi.model.UpdateApplications404Response;
import uk.ac.hdruk.gatewayapi.model.UpdateWidget200Response;
import uk.ac.hdruk.gatewayapi.model.UpdateWidgetRequest;
import uk.ac.hdruk.gatewayapi.model.WidgetAnalytics200Response;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class WidgetsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public WidgetsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public WidgetsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for createWidget
     * @param teamId Team ID the widget belongs to (required)
     * @param createWidgetRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Widget created successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Validation failed </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createWidgetCall(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull CreateWidgetRequest createWidgetRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createWidgetRequest;

        // create path and map variables
        String localVarPath = "/api/v1/teams/{teamId}/widgets"
            .replace("{" + "teamId" + "}", localVarApiClient.escapeString(teamId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createWidgetValidateBeforeCall(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull CreateWidgetRequest createWidgetRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'teamId' is set
        if (teamId == null) {
            throw new ApiException("Missing the required parameter 'teamId' when calling createWidget(Async)");
        }

        // verify the required parameter 'createWidgetRequest' is set
        if (createWidgetRequest == null) {
            throw new ApiException("Missing the required parameter 'createWidgetRequest' when calling createWidget(Async)");
        }

        return createWidgetCall(teamId, createWidgetRequest, _callback);

    }

    /**
     * Create a new widget
     * Creates a new widget for a given team
     * @param teamId Team ID the widget belongs to (required)
     * @param createWidgetRequest  (required)
     * @return CreateWidget201Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Widget created successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Validation failed </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Server error </td><td>  -  </td></tr>
     </table>
     */
    public CreateWidget201Response createWidget(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull CreateWidgetRequest createWidgetRequest) throws ApiException {
        ApiResponse<CreateWidget201Response> localVarResp = createWidgetWithHttpInfo(teamId, createWidgetRequest);
        return localVarResp.getData();
    }

    /**
     * Create a new widget
     * Creates a new widget for a given team
     * @param teamId Team ID the widget belongs to (required)
     * @param createWidgetRequest  (required)
     * @return ApiResponse&lt;CreateWidget201Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Widget created successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Validation failed </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Server error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CreateWidget201Response> createWidgetWithHttpInfo(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull CreateWidgetRequest createWidgetRequest) throws ApiException {
        okhttp3.Call localVarCall = createWidgetValidateBeforeCall(teamId, createWidgetRequest, null);
        Type localVarReturnType = new TypeToken<CreateWidget201Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create a new widget (asynchronously)
     * Creates a new widget for a given team
     * @param teamId Team ID the widget belongs to (required)
     * @param createWidgetRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Widget created successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Validation failed </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createWidgetAsync(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull CreateWidgetRequest createWidgetRequest, final ApiCallback<CreateWidget201Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = createWidgetValidateBeforeCall(teamId, createWidgetRequest, _callback);
        Type localVarReturnType = new TypeToken<CreateWidget201Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deleteWidget
     * @param teamId Team ID (required)
     * @param id Widget ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 404 </td><td> Widget not found </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> Widget deleted successfully </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteWidgetCall(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/teams/{teamId}/widgets/{id}"
            .replace("{" + "teamId" + "}", localVarApiClient.escapeString(teamId.toString()))
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteWidgetValidateBeforeCall(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'teamId' is set
        if (teamId == null) {
            throw new ApiException("Missing the required parameter 'teamId' when calling deleteWidget(Async)");
        }

        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling deleteWidget(Async)");
        }

        return deleteWidgetCall(teamId, id, _callback);

    }

    /**
     * Delete a widget
     * Soft delete a widget belonging to a specific team
     * @param teamId Team ID (required)
     * @param id Widget ID (required)
     * @return DeleteApplications200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 404 </td><td> Widget not found </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> Widget deleted successfully </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Server error </td><td>  -  </td></tr>
     </table>
     */
    public DeleteApplications200Response deleteWidget(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer id) throws ApiException {
        ApiResponse<DeleteApplications200Response> localVarResp = deleteWidgetWithHttpInfo(teamId, id);
        return localVarResp.getData();
    }

    /**
     * Delete a widget
     * Soft delete a widget belonging to a specific team
     * @param teamId Team ID (required)
     * @param id Widget ID (required)
     * @return ApiResponse&lt;DeleteApplications200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 404 </td><td> Widget not found </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> Widget deleted successfully </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Server error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<DeleteApplications200Response> deleteWidgetWithHttpInfo(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer id) throws ApiException {
        okhttp3.Call localVarCall = deleteWidgetValidateBeforeCall(teamId, id, null);
        Type localVarReturnType = new TypeToken<DeleteApplications200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Delete a widget (asynchronously)
     * Soft delete a widget belonging to a specific team
     * @param teamId Team ID (required)
     * @param id Widget ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 404 </td><td> Widget not found </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> Widget deleted successfully </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteWidgetAsync(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer id, final ApiCallback<DeleteApplications200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteWidgetValidateBeforeCall(teamId, id, _callback);
        Type localVarReturnType = new TypeToken<DeleteApplications200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for fetchAllWidgets
     * @param teamId Team ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call fetchAllWidgetsCall(@javax.annotation.Nonnull Integer teamId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/teams/{teamId}/widgets"
            .replace("{" + "teamId" + "}", localVarApiClient.escapeString(teamId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call fetchAllWidgetsValidateBeforeCall(@javax.annotation.Nonnull Integer teamId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'teamId' is set
        if (teamId == null) {
            throw new ApiException("Missing the required parameter 'teamId' when calling fetchAllWidgets(Async)");
        }

        return fetchAllWidgetsCall(teamId, _callback);

    }

    /**
     * WidgetController@index
     * Get All Widgets
     * @param teamId Team ID (required)
     * @return FetchAllWidgets200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
     </table>
     */
    public FetchAllWidgets200Response fetchAllWidgets(@javax.annotation.Nonnull Integer teamId) throws ApiException {
        ApiResponse<FetchAllWidgets200Response> localVarResp = fetchAllWidgetsWithHttpInfo(teamId);
        return localVarResp.getData();
    }

    /**
     * WidgetController@index
     * Get All Widgets
     * @param teamId Team ID (required)
     * @return ApiResponse&lt;FetchAllWidgets200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<FetchAllWidgets200Response> fetchAllWidgetsWithHttpInfo(@javax.annotation.Nonnull Integer teamId) throws ApiException {
        okhttp3.Call localVarCall = fetchAllWidgetsValidateBeforeCall(teamId, null);
        Type localVarReturnType = new TypeToken<FetchAllWidgets200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * WidgetController@index (asynchronously)
     * Get All Widgets
     * @param teamId Team ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call fetchAllWidgetsAsync(@javax.annotation.Nonnull Integer teamId, final ApiCallback<FetchAllWidgets200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = fetchAllWidgetsValidateBeforeCall(teamId, _callback);
        Type localVarReturnType = new TypeToken<FetchAllWidgets200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for fetchWidget
     * @param teamId Team ID (required)
     * @param id Widget ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Widget not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call fetchWidgetCall(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/teams/{teamId}/widgets/{id}"
            .replace("{" + "teamId" + "}", localVarApiClient.escapeString(teamId.toString()))
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call fetchWidgetValidateBeforeCall(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'teamId' is set
        if (teamId == null) {
            throw new ApiException("Missing the required parameter 'teamId' when calling fetchWidget(Async)");
        }

        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling fetchWidget(Async)");
        }

        return fetchWidgetCall(teamId, id, _callback);

    }

    /**
     * WidgetController@retrieve
     * Get a single Widget
     * @param teamId Team ID (required)
     * @param id Widget ID (required)
     * @return FetchWidget200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Widget not found </td><td>  -  </td></tr>
     </table>
     */
    public FetchWidget200Response fetchWidget(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer id) throws ApiException {
        ApiResponse<FetchWidget200Response> localVarResp = fetchWidgetWithHttpInfo(teamId, id);
        return localVarResp.getData();
    }

    /**
     * WidgetController@retrieve
     * Get a single Widget
     * @param teamId Team ID (required)
     * @param id Widget ID (required)
     * @return ApiResponse&lt;FetchWidget200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Widget not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<FetchWidget200Response> fetchWidgetWithHttpInfo(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer id) throws ApiException {
        okhttp3.Call localVarCall = fetchWidgetValidateBeforeCall(teamId, id, null);
        Type localVarReturnType = new TypeToken<FetchWidget200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * WidgetController@retrieve (asynchronously)
     * Get a single Widget
     * @param teamId Team ID (required)
     * @param id Widget ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success response </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Widget not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call fetchWidgetAsync(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer id, final ApiCallback<FetchWidget200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = fetchWidgetValidateBeforeCall(teamId, id, _callback);
        Type localVarReturnType = new TypeToken<FetchWidget200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for fetchWidgetDataSources
     * @param teamId Team ID (required)
     * @param teamIds Comma-separated list of team IDs to filter data (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Aggregated data retrieved successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid or missing teamIds parameter </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call fetchWidgetDataSourcesCall(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull String teamIds, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/teams/{teamId}/widgets/data"
            .replace("{" + "teamId" + "}", localVarApiClient.escapeString(teamId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (teamIds != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("team_ids", teamIds));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call fetchWidgetDataSourcesValidateBeforeCall(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull String teamIds, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'teamId' is set
        if (teamId == null) {
            throw new ApiException("Missing the required parameter 'teamId' when calling fetchWidgetDataSources(Async)");
        }

        // verify the required parameter 'teamIds' is set
        if (teamIds == null) {
            throw new ApiException("Missing the required parameter 'teamIds' when calling fetchWidgetDataSources(Async)");
        }

        return fetchWidgetDataSourcesCall(teamId, teamIds, _callback);

    }

    /**
     * WidgetController@getWidgetData
     * Fetch lightweight data (id, name, etc.) for multiple teams across datasets, tools, collections, and DURS
     * @param teamId Team ID (required)
     * @param teamIds Comma-separated list of team IDs to filter data (required)
     * @return FetchWidgetDataSources200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Aggregated data retrieved successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid or missing teamIds parameter </td><td>  -  </td></tr>
     </table>
     */
    public FetchWidgetDataSources200Response fetchWidgetDataSources(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull String teamIds) throws ApiException {
        ApiResponse<FetchWidgetDataSources200Response> localVarResp = fetchWidgetDataSourcesWithHttpInfo(teamId, teamIds);
        return localVarResp.getData();
    }

    /**
     * WidgetController@getWidgetData
     * Fetch lightweight data (id, name, etc.) for multiple teams across datasets, tools, collections, and DURS
     * @param teamId Team ID (required)
     * @param teamIds Comma-separated list of team IDs to filter data (required)
     * @return ApiResponse&lt;FetchWidgetDataSources200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Aggregated data retrieved successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid or missing teamIds parameter </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<FetchWidgetDataSources200Response> fetchWidgetDataSourcesWithHttpInfo(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull String teamIds) throws ApiException {
        okhttp3.Call localVarCall = fetchWidgetDataSourcesValidateBeforeCall(teamId, teamIds, null);
        Type localVarReturnType = new TypeToken<FetchWidgetDataSources200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * WidgetController@getWidgetData (asynchronously)
     * Fetch lightweight data (id, name, etc.) for multiple teams across datasets, tools, collections, and DURS
     * @param teamId Team ID (required)
     * @param teamIds Comma-separated list of team IDs to filter data (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Aggregated data retrieved successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid or missing teamIds parameter </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call fetchWidgetDataSourcesAsync(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull String teamIds, final ApiCallback<FetchWidgetDataSources200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = fetchWidgetDataSourcesValidateBeforeCall(teamId, teamIds, _callback);
        Type localVarReturnType = new TypeToken<FetchWidgetDataSources200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for retrieveWidgetData
     * @param teamId Team ID (required)
     * @param id Widget ID (required)
     * @param domainOrigin Optional domain URL to check against the widget&#39;s permitted_domains list (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 403 </td><td> Forbidden — domain not permitted for this widget </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> Widget data retrieved successfully </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Widget not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call retrieveWidgetDataCall(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull String domainOrigin, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/teams/{teamId}/widgets/{id}/data"
            .replace("{" + "teamId" + "}", localVarApiClient.escapeString(teamId.toString()))
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (domainOrigin != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("domain_origin", domainOrigin));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call retrieveWidgetDataValidateBeforeCall(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull String domainOrigin, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'teamId' is set
        if (teamId == null) {
            throw new ApiException("Missing the required parameter 'teamId' when calling retrieveWidgetData(Async)");
        }

        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling retrieveWidgetData(Async)");
        }

        // verify the required parameter 'domainOrigin' is set
        if (domainOrigin == null) {
            throw new ApiException("Missing the required parameter 'domainOrigin' when calling retrieveWidgetData(Async)");
        }

        return retrieveWidgetDataCall(teamId, id, domainOrigin, _callback);

    }

    /**
     * Retrieve data related to a widget
     * Fetches datasets, data uses, scripts, and collections linked to a widget
     * @param teamId Team ID (required)
     * @param id Widget ID (required)
     * @param domainOrigin Optional domain URL to check against the widget&#39;s permitted_domains list (required)
     * @return RetrieveWidgetData200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 403 </td><td> Forbidden — domain not permitted for this widget </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> Widget data retrieved successfully </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Widget not found </td><td>  -  </td></tr>
     </table>
     */
    public RetrieveWidgetData200Response retrieveWidgetData(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull String domainOrigin) throws ApiException {
        ApiResponse<RetrieveWidgetData200Response> localVarResp = retrieveWidgetDataWithHttpInfo(teamId, id, domainOrigin);
        return localVarResp.getData();
    }

    /**
     * Retrieve data related to a widget
     * Fetches datasets, data uses, scripts, and collections linked to a widget
     * @param teamId Team ID (required)
     * @param id Widget ID (required)
     * @param domainOrigin Optional domain URL to check against the widget&#39;s permitted_domains list (required)
     * @return ApiResponse&lt;RetrieveWidgetData200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 403 </td><td> Forbidden — domain not permitted for this widget </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> Widget data retrieved successfully </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Widget not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<RetrieveWidgetData200Response> retrieveWidgetDataWithHttpInfo(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull String domainOrigin) throws ApiException {
        okhttp3.Call localVarCall = retrieveWidgetDataValidateBeforeCall(teamId, id, domainOrigin, null);
        Type localVarReturnType = new TypeToken<RetrieveWidgetData200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieve data related to a widget (asynchronously)
     * Fetches datasets, data uses, scripts, and collections linked to a widget
     * @param teamId Team ID (required)
     * @param id Widget ID (required)
     * @param domainOrigin Optional domain URL to check against the widget&#39;s permitted_domains list (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 403 </td><td> Forbidden — domain not permitted for this widget </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> Widget data retrieved successfully </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Widget not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call retrieveWidgetDataAsync(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull String domainOrigin, final ApiCallback<RetrieveWidgetData200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = retrieveWidgetDataValidateBeforeCall(teamId, id, domainOrigin, _callback);
        Type localVarReturnType = new TypeToken<RetrieveWidgetData200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for trackWidgetEvent
     * @param teamId  (required)
     * @param id  (required)
     * @param trackWidgetEventRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Event recorded </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Widget not found </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call trackWidgetEventCall(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull TrackWidgetEventRequest trackWidgetEventRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = trackWidgetEventRequest;

        // create path and map variables
        String localVarPath = "/api/v1/teams/{teamId}/widgets/{id}/track"
            .replace("{" + "teamId" + "}", localVarApiClient.escapeString(teamId.toString()))
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call trackWidgetEventValidateBeforeCall(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull TrackWidgetEventRequest trackWidgetEventRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'teamId' is set
        if (teamId == null) {
            throw new ApiException("Missing the required parameter 'teamId' when calling trackWidgetEvent(Async)");
        }

        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling trackWidgetEvent(Async)");
        }

        // verify the required parameter 'trackWidgetEventRequest' is set
        if (trackWidgetEventRequest == null) {
            throw new ApiException("Missing the required parameter 'trackWidgetEventRequest' when calling trackWidgetEvent(Async)");
        }

        return trackWidgetEventCall(teamId, id, trackWidgetEventRequest, _callback);

    }

    /**
     * Record a widget analytics event
     * Public endpoint for frontend clients to record user interactions with a widget (page views, code copies, gateway clicks, searches). No authentication required.
     * @param teamId  (required)
     * @param id  (required)
     * @param trackWidgetEventRequest  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Event recorded </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Widget not found </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation error </td><td>  -  </td></tr>
     </table>
     */
    public void trackWidgetEvent(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull TrackWidgetEventRequest trackWidgetEventRequest) throws ApiException {
        trackWidgetEventWithHttpInfo(teamId, id, trackWidgetEventRequest);
    }

    /**
     * Record a widget analytics event
     * Public endpoint for frontend clients to record user interactions with a widget (page views, code copies, gateway clicks, searches). No authentication required.
     * @param teamId  (required)
     * @param id  (required)
     * @param trackWidgetEventRequest  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Event recorded </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Widget not found </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> trackWidgetEventWithHttpInfo(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull TrackWidgetEventRequest trackWidgetEventRequest) throws ApiException {
        okhttp3.Call localVarCall = trackWidgetEventValidateBeforeCall(teamId, id, trackWidgetEventRequest, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Record a widget analytics event (asynchronously)
     * Public endpoint for frontend clients to record user interactions with a widget (page views, code copies, gateway clicks, searches). No authentication required.
     * @param teamId  (required)
     * @param id  (required)
     * @param trackWidgetEventRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Event recorded </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Widget not found </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call trackWidgetEventAsync(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull TrackWidgetEventRequest trackWidgetEventRequest, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = trackWidgetEventValidateBeforeCall(teamId, id, trackWidgetEventRequest, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateWidget
     * @param teamId Team ID (required)
     * @param id Widget ID (required)
     * @param updateWidgetRequest  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Widget successfully updated </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Widget not found </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateWidgetCall(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer id, @javax.annotation.Nullable UpdateWidgetRequest updateWidgetRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = updateWidgetRequest;

        // create path and map variables
        String localVarPath = "/api/v1/teams/{teamId}/widgets/{id}"
            .replace("{" + "teamId" + "}", localVarApiClient.escapeString(teamId.toString()))
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateWidgetValidateBeforeCall(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer id, @javax.annotation.Nullable UpdateWidgetRequest updateWidgetRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'teamId' is set
        if (teamId == null) {
            throw new ApiException("Missing the required parameter 'teamId' when calling updateWidget(Async)");
        }

        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling updateWidget(Async)");
        }

        return updateWidgetCall(teamId, id, updateWidgetRequest, _callback);

    }

    /**
     * Update an existing widget
     * Updates an existing widget for a given team ID
     * @param teamId Team ID (required)
     * @param id Widget ID (required)
     * @param updateWidgetRequest  (optional)
     * @return UpdateWidget200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Widget successfully updated </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Widget not found </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public UpdateWidget200Response updateWidget(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer id, @javax.annotation.Nullable UpdateWidgetRequest updateWidgetRequest) throws ApiException {
        ApiResponse<UpdateWidget200Response> localVarResp = updateWidgetWithHttpInfo(teamId, id, updateWidgetRequest);
        return localVarResp.getData();
    }

    /**
     * Update an existing widget
     * Updates an existing widget for a given team ID
     * @param teamId Team ID (required)
     * @param id Widget ID (required)
     * @param updateWidgetRequest  (optional)
     * @return ApiResponse&lt;UpdateWidget200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Widget successfully updated </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Widget not found </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<UpdateWidget200Response> updateWidgetWithHttpInfo(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer id, @javax.annotation.Nullable UpdateWidgetRequest updateWidgetRequest) throws ApiException {
        okhttp3.Call localVarCall = updateWidgetValidateBeforeCall(teamId, id, updateWidgetRequest, null);
        Type localVarReturnType = new TypeToken<UpdateWidget200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update an existing widget (asynchronously)
     * Updates an existing widget for a given team ID
     * @param teamId Team ID (required)
     * @param id Widget ID (required)
     * @param updateWidgetRequest  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Widget successfully updated </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Widget not found </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateWidgetAsync(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nonnull Integer id, @javax.annotation.Nullable UpdateWidgetRequest updateWidgetRequest, final ApiCallback<UpdateWidget200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateWidgetValidateBeforeCall(teamId, id, updateWidgetRequest, _callback);
        Type localVarReturnType = new TypeToken<UpdateWidget200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for widgetAnalytics
     * @param teamId  (required)
     * @param from Start date (Y-m-d) (optional)
     * @param to End date (Y-m-d) (optional)
     * @param groupBy Time granularity (optional, default to day)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Analytics data </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call widgetAnalyticsCall(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nullable String from, @javax.annotation.Nullable String to, @javax.annotation.Nullable String groupBy, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/teams/{teamId}/widgets/analytics"
            .replace("{" + "teamId" + "}", localVarApiClient.escapeString(teamId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (from != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("from", from));
        }

        if (to != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("to", to));
        }

        if (groupBy != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("group_by", groupBy));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call widgetAnalyticsValidateBeforeCall(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nullable String from, @javax.annotation.Nullable String to, @javax.annotation.Nullable String groupBy, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'teamId' is set
        if (teamId == null) {
            throw new ApiException("Missing the required parameter 'teamId' when calling widgetAnalytics(Async)");
        }

        return widgetAnalyticsCall(teamId, from, to, groupBy, _callback);

    }

    /**
     * Get widget analytics for a team
     * Returns aggregated event counts per widget, per event type, and over time. Supports date range filtering and time-based grouping.
     * @param teamId  (required)
     * @param from Start date (Y-m-d) (optional)
     * @param to End date (Y-m-d) (optional)
     * @param groupBy Time granularity (optional, default to day)
     * @return WidgetAnalytics200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Analytics data </td><td>  -  </td></tr>
     </table>
     */
    public WidgetAnalytics200Response widgetAnalytics(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nullable String from, @javax.annotation.Nullable String to, @javax.annotation.Nullable String groupBy) throws ApiException {
        ApiResponse<WidgetAnalytics200Response> localVarResp = widgetAnalyticsWithHttpInfo(teamId, from, to, groupBy);
        return localVarResp.getData();
    }

    /**
     * Get widget analytics for a team
     * Returns aggregated event counts per widget, per event type, and over time. Supports date range filtering and time-based grouping.
     * @param teamId  (required)
     * @param from Start date (Y-m-d) (optional)
     * @param to End date (Y-m-d) (optional)
     * @param groupBy Time granularity (optional, default to day)
     * @return ApiResponse&lt;WidgetAnalytics200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Analytics data </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<WidgetAnalytics200Response> widgetAnalyticsWithHttpInfo(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nullable String from, @javax.annotation.Nullable String to, @javax.annotation.Nullable String groupBy) throws ApiException {
        okhttp3.Call localVarCall = widgetAnalyticsValidateBeforeCall(teamId, from, to, groupBy, null);
        Type localVarReturnType = new TypeToken<WidgetAnalytics200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get widget analytics for a team (asynchronously)
     * Returns aggregated event counts per widget, per event type, and over time. Supports date range filtering and time-based grouping.
     * @param teamId  (required)
     * @param from Start date (Y-m-d) (optional)
     * @param to End date (Y-m-d) (optional)
     * @param groupBy Time granularity (optional, default to day)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Analytics data </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call widgetAnalyticsAsync(@javax.annotation.Nonnull Integer teamId, @javax.annotation.Nullable String from, @javax.annotation.Nullable String to, @javax.annotation.Nullable String groupBy, final ApiCallback<WidgetAnalytics200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = widgetAnalyticsValidateBeforeCall(teamId, from, to, groupBy, _callback);
        Type localVarReturnType = new TypeToken<WidgetAnalytics200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
