/*
 * HDRUK Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.gatewayapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import uk.ac.hdruk.gatewayapi.model.SearchDatasets200ResponseDataInnerHighlightInner;
import uk.ac.hdruk.gatewayapi.model.SearchDatasets200ResponseDataInnerSourceInner;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import uk.ac.hdruk.gatewayapi.JSON;

/**
 * SearchDatasets200ResponseDataInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-05T08:39:33.604456851Z[Etc/UTC]", comments = "Generator version: 7.24.0")
public class SearchDatasets200ResponseDataInner {
  public static final String SERIALIZED_NAME_SOURCE = "_source";
  @SerializedName(SERIALIZED_NAME_SOURCE)
  @javax.annotation.Nullable
  private List<SearchDatasets200ResponseDataInnerSourceInner> source = new ArrayList<>();

  public static final String SERIALIZED_NAME_HIGHLIGHT = "highlight";
  @SerializedName(SERIALIZED_NAME_HIGHLIGHT)
  @javax.annotation.Nullable
  private List<SearchDatasets200ResponseDataInnerHighlightInner> highlight = new ArrayList<>();

  public SearchDatasets200ResponseDataInner() {
  }

  public SearchDatasets200ResponseDataInner source(@javax.annotation.Nullable List<SearchDatasets200ResponseDataInnerSourceInner> source) {
    this.source = source;
    return this;
  }

  public SearchDatasets200ResponseDataInner addSourceItem(SearchDatasets200ResponseDataInnerSourceInner sourceItem) {
    if (this.source == null) {
      this.source = new ArrayList<>();
    }
    this.source.add(sourceItem);
    return this;
  }

  /**
   * Get source
   * @return source
   */
  @javax.annotation.Nullable
  public List<SearchDatasets200ResponseDataInnerSourceInner> getSource() {
    return source;
  }

  public void setSource(@javax.annotation.Nullable List<SearchDatasets200ResponseDataInnerSourceInner> source) {
    this.source = source;
  }


  public SearchDatasets200ResponseDataInner highlight(@javax.annotation.Nullable List<SearchDatasets200ResponseDataInnerHighlightInner> highlight) {
    this.highlight = highlight;
    return this;
  }

  public SearchDatasets200ResponseDataInner addHighlightItem(SearchDatasets200ResponseDataInnerHighlightInner highlightItem) {
    if (this.highlight == null) {
      this.highlight = new ArrayList<>();
    }
    this.highlight.add(highlightItem);
    return this;
  }

  /**
   * Get highlight
   * @return highlight
   */
  @javax.annotation.Nullable
  public List<SearchDatasets200ResponseDataInnerHighlightInner> getHighlight() {
    return highlight;
  }

  public void setHighlight(@javax.annotation.Nullable List<SearchDatasets200ResponseDataInnerHighlightInner> highlight) {
    this.highlight = highlight;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchDatasets200ResponseDataInner searchDatasets200ResponseDataInner = (SearchDatasets200ResponseDataInner) o;
    return Objects.equals(this.source, searchDatasets200ResponseDataInner.source) &&
        Objects.equals(this.highlight, searchDatasets200ResponseDataInner.highlight);
  }

  @Override
  public int hashCode() {
    return Objects.hash(source, highlight);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchDatasets200ResponseDataInner {\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    highlight: ").append(toIndentedString(highlight)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("_source", "highlight"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SearchDatasets200ResponseDataInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SearchDatasets200ResponseDataInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in SearchDatasets200ResponseDataInner is not found in the empty JSON string", SearchDatasets200ResponseDataInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SearchDatasets200ResponseDataInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `SearchDatasets200ResponseDataInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("_source") != null && !jsonObj.get("_source").isJsonNull()) {
        JsonArray jsonArraysource = jsonObj.getAsJsonArray("_source");
        if (jsonArraysource != null) {
          // ensure the json data is an array
          if (!jsonObj.get("_source").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `_source` to be an array in the JSON string but got `%s`", jsonObj.get("_source").toString()));
          }

          // validate the optional field `_source` (array)
          for (int i = 0; i < jsonArraysource.size(); i++) {
            SearchDatasets200ResponseDataInnerSourceInner.validateJsonElement(jsonArraysource.get(i));
          };
        }
      }
      if (jsonObj.get("highlight") != null && !jsonObj.get("highlight").isJsonNull()) {
        JsonArray jsonArrayhighlight = jsonObj.getAsJsonArray("highlight");
        if (jsonArrayhighlight != null) {
          // ensure the json data is an array
          if (!jsonObj.get("highlight").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `highlight` to be an array in the JSON string but got `%s`", jsonObj.get("highlight").toString()));
          }

          // validate the optional field `highlight` (array)
          for (int i = 0; i < jsonArrayhighlight.size(); i++) {
            SearchDatasets200ResponseDataInnerHighlightInner.validateJsonElement(jsonArrayhighlight.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SearchDatasets200ResponseDataInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SearchDatasets200ResponseDataInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SearchDatasets200ResponseDataInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SearchDatasets200ResponseDataInner.class));

       return (TypeAdapter<T>) new TypeAdapter<SearchDatasets200ResponseDataInner>() {
           @Override
           public void write(JsonWriter out, SearchDatasets200ResponseDataInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SearchDatasets200ResponseDataInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SearchDatasets200ResponseDataInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SearchDatasets200ResponseDataInner
   * @throws IOException if the JSON string is invalid with respect to SearchDatasets200ResponseDataInner
   */
  public static SearchDatasets200ResponseDataInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SearchDatasets200ResponseDataInner.class);
  }

  /**
   * Convert an instance of SearchDatasets200ResponseDataInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

