/*
 * HDRUK Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.gatewayapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import uk.ac.hdruk.gatewayapi.JSON;

/**
 * A data custodian team that owns datasets and manages data access
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-17T15:40:23.780937896Z[Etc/UTC]", comments = "Generator version: 7.24.0")
public class Team {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Integer id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_ENABLED = "enabled";
  @SerializedName(SERIALIZED_NAME_ENABLED)
  @javax.annotation.Nullable
  private Boolean enabled;

  public static final String SERIALIZED_NAME_ALLOWS_MESSAGING = "allows_messaging";
  @SerializedName(SERIALIZED_NAME_ALLOWS_MESSAGING)
  @javax.annotation.Nullable
  private Boolean allowsMessaging;

  public static final String SERIALIZED_NAME_WORKFLOW_ENABLED = "workflow_enabled";
  @SerializedName(SERIALIZED_NAME_WORKFLOW_ENABLED)
  @javax.annotation.Nullable
  private Boolean workflowEnabled;

  public static final String SERIALIZED_NAME_ACCESS_REQUESTS_MANAGEMENT = "access_requests_management";
  @SerializedName(SERIALIZED_NAME_ACCESS_REQUESTS_MANAGEMENT)
  @javax.annotation.Nullable
  private Boolean accessRequestsManagement;

  public static final String SERIALIZED_NAME_USES5_SAFES = "uses_5_safes";
  @SerializedName(SERIALIZED_NAME_USES5_SAFES)
  @javax.annotation.Nullable
  private Boolean uses5Safes;

  public static final String SERIALIZED_NAME_IS_ADMIN = "is_admin";
  @SerializedName(SERIALIZED_NAME_IS_ADMIN)
  @javax.annotation.Nullable
  private Boolean isAdmin;

  public static final String SERIALIZED_NAME_MEMBER_OF = "member_of";
  @SerializedName(SERIALIZED_NAME_MEMBER_OF)
  @javax.annotation.Nullable
  private String memberOf;

  public static final String SERIALIZED_NAME_CONTACT_POINT = "contact_point";
  @SerializedName(SERIALIZED_NAME_CONTACT_POINT)
  @javax.annotation.Nullable
  private String contactPoint;

  public static final String SERIALIZED_NAME_NOTIFICATION_STATUS = "notification_status";
  @SerializedName(SERIALIZED_NAME_NOTIFICATION_STATUS)
  @javax.annotation.Nullable
  private Boolean notificationStatus;

  public static final String SERIALIZED_NAME_IS_QUESTION_BANK = "is_question_bank";
  @SerializedName(SERIALIZED_NAME_IS_QUESTION_BANK)
  @javax.annotation.Nullable
  private Boolean isQuestionBank;

  public static final String SERIALIZED_NAME_TEAM_LOGO = "team_logo";
  @SerializedName(SERIALIZED_NAME_TEAM_LOGO)
  @javax.annotation.Nullable
  private String teamLogo;

  public static final String SERIALIZED_NAME_INTRODUCTION = "introduction";
  @SerializedName(SERIALIZED_NAME_INTRODUCTION)
  @javax.annotation.Nullable
  private String introduction;

  public static final String SERIALIZED_NAME_DAR_MODAL_CONTENT = "dar_modal_content";
  @SerializedName(SERIALIZED_NAME_DAR_MODAL_CONTENT)
  @javax.annotation.Nullable
  private String darModalContent;

  public static final String SERIALIZED_NAME_DAR_MODAL_HEADER = "dar_modal_header";
  @SerializedName(SERIALIZED_NAME_DAR_MODAL_HEADER)
  @javax.annotation.Nullable
  private String darModalHeader;

  public static final String SERIALIZED_NAME_DAR_MODAL_FOOTER = "dar_modal_footer";
  @SerializedName(SERIALIZED_NAME_DAR_MODAL_FOOTER)
  @javax.annotation.Nullable
  private String darModalFooter;

  public static final String SERIALIZED_NAME_SERVICE = "service";
  @SerializedName(SERIALIZED_NAME_SERVICE)
  @javax.annotation.Nullable
  private String service;

  public static final String SERIALIZED_NAME_IS_DAR = "is_dar";
  @SerializedName(SERIALIZED_NAME_IS_DAR)
  @javax.annotation.Nullable
  private Boolean isDar;

  public static final String SERIALIZED_NAME_PID = "pid";
  @SerializedName(SERIALIZED_NAME_PID)
  @javax.annotation.Nullable
  private String pid;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime updatedAt;

  public Team() {
  }

  public Team id(@javax.annotation.Nullable Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public Integer getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable Integer id) {
    this.id = id;
  }


  public Team name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public Team enabled(@javax.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

  /**
   * Get enabled
   * @return enabled
   */
  @javax.annotation.Nullable
  public Boolean getEnabled() {
    return enabled;
  }

  public void setEnabled(@javax.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
  }


  public Team allowsMessaging(@javax.annotation.Nullable Boolean allowsMessaging) {
    this.allowsMessaging = allowsMessaging;
    return this;
  }

  /**
   * Get allowsMessaging
   * @return allowsMessaging
   */
  @javax.annotation.Nullable
  public Boolean getAllowsMessaging() {
    return allowsMessaging;
  }

  public void setAllowsMessaging(@javax.annotation.Nullable Boolean allowsMessaging) {
    this.allowsMessaging = allowsMessaging;
  }


  public Team workflowEnabled(@javax.annotation.Nullable Boolean workflowEnabled) {
    this.workflowEnabled = workflowEnabled;
    return this;
  }

  /**
   * Get workflowEnabled
   * @return workflowEnabled
   */
  @javax.annotation.Nullable
  public Boolean getWorkflowEnabled() {
    return workflowEnabled;
  }

  public void setWorkflowEnabled(@javax.annotation.Nullable Boolean workflowEnabled) {
    this.workflowEnabled = workflowEnabled;
  }


  public Team accessRequestsManagement(@javax.annotation.Nullable Boolean accessRequestsManagement) {
    this.accessRequestsManagement = accessRequestsManagement;
    return this;
  }

  /**
   * Get accessRequestsManagement
   * @return accessRequestsManagement
   */
  @javax.annotation.Nullable
  public Boolean getAccessRequestsManagement() {
    return accessRequestsManagement;
  }

  public void setAccessRequestsManagement(@javax.annotation.Nullable Boolean accessRequestsManagement) {
    this.accessRequestsManagement = accessRequestsManagement;
  }


  public Team uses5Safes(@javax.annotation.Nullable Boolean uses5Safes) {
    this.uses5Safes = uses5Safes;
    return this;
  }

  /**
   * Get uses5Safes
   * @return uses5Safes
   */
  @javax.annotation.Nullable
  public Boolean getUses5Safes() {
    return uses5Safes;
  }

  public void setUses5Safes(@javax.annotation.Nullable Boolean uses5Safes) {
    this.uses5Safes = uses5Safes;
  }


  public Team isAdmin(@javax.annotation.Nullable Boolean isAdmin) {
    this.isAdmin = isAdmin;
    return this;
  }

  /**
   * Get isAdmin
   * @return isAdmin
   */
  @javax.annotation.Nullable
  public Boolean getIsAdmin() {
    return isAdmin;
  }

  public void setIsAdmin(@javax.annotation.Nullable Boolean isAdmin) {
    this.isAdmin = isAdmin;
  }


  public Team memberOf(@javax.annotation.Nullable String memberOf) {
    this.memberOf = memberOf;
    return this;
  }

  /**
   * Get memberOf
   * @return memberOf
   */
  @javax.annotation.Nullable
  public String getMemberOf() {
    return memberOf;
  }

  public void setMemberOf(@javax.annotation.Nullable String memberOf) {
    this.memberOf = memberOf;
  }


  public Team contactPoint(@javax.annotation.Nullable String contactPoint) {
    this.contactPoint = contactPoint;
    return this;
  }

  /**
   * Get contactPoint
   * @return contactPoint
   */
  @javax.annotation.Nullable
  public String getContactPoint() {
    return contactPoint;
  }

  public void setContactPoint(@javax.annotation.Nullable String contactPoint) {
    this.contactPoint = contactPoint;
  }


  public Team notificationStatus(@javax.annotation.Nullable Boolean notificationStatus) {
    this.notificationStatus = notificationStatus;
    return this;
  }

  /**
   * Get notificationStatus
   * @return notificationStatus
   */
  @javax.annotation.Nullable
  public Boolean getNotificationStatus() {
    return notificationStatus;
  }

  public void setNotificationStatus(@javax.annotation.Nullable Boolean notificationStatus) {
    this.notificationStatus = notificationStatus;
  }


  public Team isQuestionBank(@javax.annotation.Nullable Boolean isQuestionBank) {
    this.isQuestionBank = isQuestionBank;
    return this;
  }

  /**
   * Get isQuestionBank
   * @return isQuestionBank
   */
  @javax.annotation.Nullable
  public Boolean getIsQuestionBank() {
    return isQuestionBank;
  }

  public void setIsQuestionBank(@javax.annotation.Nullable Boolean isQuestionBank) {
    this.isQuestionBank = isQuestionBank;
  }


  public Team teamLogo(@javax.annotation.Nullable String teamLogo) {
    this.teamLogo = teamLogo;
    return this;
  }

  /**
   * Get teamLogo
   * @return teamLogo
   */
  @javax.annotation.Nullable
  public String getTeamLogo() {
    return teamLogo;
  }

  public void setTeamLogo(@javax.annotation.Nullable String teamLogo) {
    this.teamLogo = teamLogo;
  }


  public Team introduction(@javax.annotation.Nullable String introduction) {
    this.introduction = introduction;
    return this;
  }

  /**
   * Get introduction
   * @return introduction
   */
  @javax.annotation.Nullable
  public String getIntroduction() {
    return introduction;
  }

  public void setIntroduction(@javax.annotation.Nullable String introduction) {
    this.introduction = introduction;
  }


  public Team darModalContent(@javax.annotation.Nullable String darModalContent) {
    this.darModalContent = darModalContent;
    return this;
  }

  /**
   * Get darModalContent
   * @return darModalContent
   */
  @javax.annotation.Nullable
  public String getDarModalContent() {
    return darModalContent;
  }

  public void setDarModalContent(@javax.annotation.Nullable String darModalContent) {
    this.darModalContent = darModalContent;
  }


  public Team darModalHeader(@javax.annotation.Nullable String darModalHeader) {
    this.darModalHeader = darModalHeader;
    return this;
  }

  /**
   * Get darModalHeader
   * @return darModalHeader
   */
  @javax.annotation.Nullable
  public String getDarModalHeader() {
    return darModalHeader;
  }

  public void setDarModalHeader(@javax.annotation.Nullable String darModalHeader) {
    this.darModalHeader = darModalHeader;
  }


  public Team darModalFooter(@javax.annotation.Nullable String darModalFooter) {
    this.darModalFooter = darModalFooter;
    return this;
  }

  /**
   * Get darModalFooter
   * @return darModalFooter
   */
  @javax.annotation.Nullable
  public String getDarModalFooter() {
    return darModalFooter;
  }

  public void setDarModalFooter(@javax.annotation.Nullable String darModalFooter) {
    this.darModalFooter = darModalFooter;
  }


  public Team service(@javax.annotation.Nullable String service) {
    this.service = service;
    return this;
  }

  /**
   * Get service
   * @return service
   */
  @javax.annotation.Nullable
  public String getService() {
    return service;
  }

  public void setService(@javax.annotation.Nullable String service) {
    this.service = service;
  }


  public Team isDar(@javax.annotation.Nullable Boolean isDar) {
    this.isDar = isDar;
    return this;
  }

  /**
   * Get isDar
   * @return isDar
   */
  @javax.annotation.Nullable
  public Boolean getIsDar() {
    return isDar;
  }

  public void setIsDar(@javax.annotation.Nullable Boolean isDar) {
    this.isDar = isDar;
  }


  public Team pid(@javax.annotation.Nullable String pid) {
    this.pid = pid;
    return this;
  }

  /**
   * Public identifier, cast to string
   * @return pid
   */
  @javax.annotation.Nullable
  public String getPid() {
    return pid;
  }

  public void setPid(@javax.annotation.Nullable String pid) {
    this.pid = pid;
  }


  public Team createdAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public Team updatedAt(@javax.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@javax.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Team team = (Team) o;
    return Objects.equals(this.id, team.id) &&
        Objects.equals(this.name, team.name) &&
        Objects.equals(this.enabled, team.enabled) &&
        Objects.equals(this.allowsMessaging, team.allowsMessaging) &&
        Objects.equals(this.workflowEnabled, team.workflowEnabled) &&
        Objects.equals(this.accessRequestsManagement, team.accessRequestsManagement) &&
        Objects.equals(this.uses5Safes, team.uses5Safes) &&
        Objects.equals(this.isAdmin, team.isAdmin) &&
        Objects.equals(this.memberOf, team.memberOf) &&
        Objects.equals(this.contactPoint, team.contactPoint) &&
        Objects.equals(this.notificationStatus, team.notificationStatus) &&
        Objects.equals(this.isQuestionBank, team.isQuestionBank) &&
        Objects.equals(this.teamLogo, team.teamLogo) &&
        Objects.equals(this.introduction, team.introduction) &&
        Objects.equals(this.darModalContent, team.darModalContent) &&
        Objects.equals(this.darModalHeader, team.darModalHeader) &&
        Objects.equals(this.darModalFooter, team.darModalFooter) &&
        Objects.equals(this.service, team.service) &&
        Objects.equals(this.isDar, team.isDar) &&
        Objects.equals(this.pid, team.pid) &&
        Objects.equals(this.createdAt, team.createdAt) &&
        Objects.equals(this.updatedAt, team.updatedAt);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, enabled, allowsMessaging, workflowEnabled, accessRequestsManagement, uses5Safes, isAdmin, memberOf, contactPoint, notificationStatus, isQuestionBank, teamLogo, introduction, darModalContent, darModalHeader, darModalFooter, service, isDar, pid, createdAt, updatedAt);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Team {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    allowsMessaging: ").append(toIndentedString(allowsMessaging)).append("\n");
    sb.append("    workflowEnabled: ").append(toIndentedString(workflowEnabled)).append("\n");
    sb.append("    accessRequestsManagement: ").append(toIndentedString(accessRequestsManagement)).append("\n");
    sb.append("    uses5Safes: ").append(toIndentedString(uses5Safes)).append("\n");
    sb.append("    isAdmin: ").append(toIndentedString(isAdmin)).append("\n");
    sb.append("    memberOf: ").append(toIndentedString(memberOf)).append("\n");
    sb.append("    contactPoint: ").append(toIndentedString(contactPoint)).append("\n");
    sb.append("    notificationStatus: ").append(toIndentedString(notificationStatus)).append("\n");
    sb.append("    isQuestionBank: ").append(toIndentedString(isQuestionBank)).append("\n");
    sb.append("    teamLogo: ").append(toIndentedString(teamLogo)).append("\n");
    sb.append("    introduction: ").append(toIndentedString(introduction)).append("\n");
    sb.append("    darModalContent: ").append(toIndentedString(darModalContent)).append("\n");
    sb.append("    darModalHeader: ").append(toIndentedString(darModalHeader)).append("\n");
    sb.append("    darModalFooter: ").append(toIndentedString(darModalFooter)).append("\n");
    sb.append("    service: ").append(toIndentedString(service)).append("\n");
    sb.append("    isDar: ").append(toIndentedString(isDar)).append("\n");
    sb.append("    pid: ").append(toIndentedString(pid)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "name", "enabled", "allows_messaging", "workflow_enabled", "access_requests_management", "uses_5_safes", "is_admin", "member_of", "contact_point", "notification_status", "is_question_bank", "team_logo", "introduction", "dar_modal_content", "dar_modal_header", "dar_modal_footer", "service", "is_dar", "pid", "created_at", "updated_at"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Team
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Team.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in Team is not found in the empty JSON string", Team.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Team.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Team` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("member_of") != null && !jsonObj.get("member_of").isJsonNull()) && !jsonObj.get("member_of").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `member_of` to be a primitive type in the JSON string but got `%s`", jsonObj.get("member_of").toString()));
      }
      if ((jsonObj.get("contact_point") != null && !jsonObj.get("contact_point").isJsonNull()) && !jsonObj.get("contact_point").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `contact_point` to be a primitive type in the JSON string but got `%s`", jsonObj.get("contact_point").toString()));
      }
      if ((jsonObj.get("team_logo") != null && !jsonObj.get("team_logo").isJsonNull()) && !jsonObj.get("team_logo").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `team_logo` to be a primitive type in the JSON string but got `%s`", jsonObj.get("team_logo").toString()));
      }
      if ((jsonObj.get("introduction") != null && !jsonObj.get("introduction").isJsonNull()) && !jsonObj.get("introduction").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `introduction` to be a primitive type in the JSON string but got `%s`", jsonObj.get("introduction").toString()));
      }
      if ((jsonObj.get("dar_modal_content") != null && !jsonObj.get("dar_modal_content").isJsonNull()) && !jsonObj.get("dar_modal_content").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `dar_modal_content` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dar_modal_content").toString()));
      }
      if ((jsonObj.get("dar_modal_header") != null && !jsonObj.get("dar_modal_header").isJsonNull()) && !jsonObj.get("dar_modal_header").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `dar_modal_header` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dar_modal_header").toString()));
      }
      if ((jsonObj.get("dar_modal_footer") != null && !jsonObj.get("dar_modal_footer").isJsonNull()) && !jsonObj.get("dar_modal_footer").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `dar_modal_footer` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dar_modal_footer").toString()));
      }
      if ((jsonObj.get("service") != null && !jsonObj.get("service").isJsonNull()) && !jsonObj.get("service").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `service` to be a primitive type in the JSON string but got `%s`", jsonObj.get("service").toString()));
      }
      if ((jsonObj.get("pid") != null && !jsonObj.get("pid").isJsonNull()) && !jsonObj.get("pid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `pid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pid").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Team.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Team' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Team> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Team.class));

       return (TypeAdapter<T>) new TypeAdapter<Team>() {
           @Override
           public void write(JsonWriter out, Team value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Team read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Team given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Team
   * @throws IOException if the JSON string is invalid with respect to Team
   */
  public static Team fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Team.class);
  }

  /**
   * Convert an instance of Team to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

