/*
 * HDRUK Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.gatewayapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import uk.ac.hdruk.gatewayapi.model.UpdateUserDarApplicationRequestAnswersInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateUserDarApplicationAnswersRequest
 */
public class CreateUserDarApplicationAnswersRequestTest {
    private final CreateUserDarApplicationAnswersRequest model = new CreateUserDarApplicationAnswersRequest();

    /**
     * Model tests for CreateUserDarApplicationAnswersRequest
     */
    @Test
    public void testCreateUserDarApplicationAnswersRequest() {
        // TODO: test CreateUserDarApplicationAnswersRequest
    }

    /**
     * Test the property 'answers'
     */
    @Test
    public void answersTest() {
        // TODO: test answers
    }

}
