/*
 * HDRUK Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.gatewayapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import uk.ac.hdruk.gatewayapi.model.CreateTeamCollectionsRequestDatasetsInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateCollectionsRequest
 */
public class CreateCollectionsRequestTest {
    private final CreateCollectionsRequest model = new CreateCollectionsRequest();

    /**
     * Model tests for CreateCollectionsRequest
     */
    @Test
    public void testCreateCollectionsRequest() {
        // TODO: test CreateCollectionsRequest
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'imageLink'
     */
    @Test
    public void imageLinkTest() {
        // TODO: test imageLink
    }

    /**
     * Test the property 'enabled'
     */
    @Test
    public void enabledTest() {
        // TODO: test enabled
    }

    /**
     * Test the property 'keywords'
     */
    @Test
    public void keywordsTest() {
        // TODO: test keywords
    }

    /**
     * Test the property 'datasets'
     */
    @Test
    public void datasetsTest() {
        // TODO: test datasets
    }

    /**
     * Test the property 'tools'
     */
    @Test
    public void toolsTest() {
        // TODO: test tools
    }

    /**
     * Test the property 'dur'
     */
    @Test
    public void durTest() {
        // TODO: test dur
    }

    /**
     * Test the property 'publications'
     */
    @Test
    public void publicationsTest() {
        // TODO: test publications
    }

    /**
     * Test the property 'collaborators'
     */
    @Test
    public void collaboratorsTest() {
        // TODO: test collaborators
    }

    /**
     * Test the property '_public'
     */
    @Test
    public void _publicTest() {
        // TODO: test _public
    }

}
