/*
 * HDRUK Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.gatewayapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FetchDataCustodianNetworkDatasetsSummary200ResponseData
 */
public class FetchDataCustodianNetworkDatasetsSummary200ResponseDataTest {
    private final FetchDataCustodianNetworkDatasetsSummary200ResponseData model = new FetchDataCustodianNetworkDatasetsSummary200ResponseData();

    /**
     * Model tests for FetchDataCustodianNetworkDatasetsSummary200ResponseData
     */
    @Test
    public void testFetchDataCustodianNetworkDatasetsSummary200ResponseData() {
        // TODO: test FetchDataCustodianNetworkDatasetsSummary200ResponseData
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'datasets'
     */
    @Test
    public void datasetsTest() {
        // TODO: test datasets
    }

    /**
     * Test the property 'datasetsTotal'
     */
    @Test
    public void datasetsTotalTest() {
        // TODO: test datasetsTotal
    }

}
