/*
 * HDRUK Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.gatewayapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import uk.ac.hdruk.gatewayapi.model.FetchTeamDarApplicationHeader200ResponseDataDatasetsInner;
import uk.ac.hdruk.gatewayapi.model.FetchTeamDarApplicationHeader200ResponseDataPrimaryApplicantInner;
import uk.ac.hdruk.gatewayapi.model.FetchTeamDarApplicationHeader200ResponseDataTeamsInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FetchTeamDarApplicationHeader200ResponseData
 */
public class FetchTeamDarApplicationHeader200ResponseDataTest {
    private final FetchTeamDarApplicationHeader200ResponseData model = new FetchTeamDarApplicationHeader200ResponseData();

    /**
     * Model tests for FetchTeamDarApplicationHeader200ResponseData
     */
    @Test
    public void testFetchTeamDarApplicationHeader200ResponseData() {
        // TODO: test FetchTeamDarApplicationHeader200ResponseData
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'deletedAt'
     */
    @Test
    public void deletedAtTest() {
        // TODO: test deletedAt
    }

    /**
     * Test the property 'applicantId'
     */
    @Test
    public void applicantIdTest() {
        // TODO: test applicantId
    }

    /**
     * Test the property 'projectTitle'
     */
    @Test
    public void projectTitleTest() {
        // TODO: test projectTitle
    }

    /**
     * Test the property 'applicationType'
     */
    @Test
    public void applicationTypeTest() {
        // TODO: test applicationType
    }

    /**
     * Test the property 'projectId'
     */
    @Test
    public void projectIdTest() {
        // TODO: test projectId
    }

    /**
     * Test the property 'isJoint'
     */
    @Test
    public void isJointTest() {
        // TODO: test isJoint
    }

    /**
     * Test the property 'approvalStatus'
     */
    @Test
    public void approvalStatusTest() {
        // TODO: test approvalStatus
    }

    /**
     * Test the property 'submissionStatus'
     */
    @Test
    public void submissionStatusTest() {
        // TODO: test submissionStatus
    }

    /**
     * Test the property 'statusReviewId'
     */
    @Test
    public void statusReviewIdTest() {
        // TODO: test statusReviewId
    }

    /**
     * Test the property 'daysSinceSubmission'
     */
    @Test
    public void daysSinceSubmissionTest() {
        // TODO: test daysSinceSubmission
    }

    /**
     * Test the property 'primaryApplicant'
     */
    @Test
    public void primaryApplicantTest() {
        // TODO: test primaryApplicant
    }

    /**
     * Test the property 'datasets'
     */
    @Test
    public void datasetsTest() {
        // TODO: test datasets
    }

    /**
     * Test the property 'teams'
     */
    @Test
    public void teamsTest() {
        // TODO: test teams
    }

}
