/*
 * HDRUK Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.gatewayapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetFederationByFederationIdAndTeamId200ResponseData
 */
public class GetFederationByFederationIdAndTeamId200ResponseDataTest {
    private final GetFederationByFederationIdAndTeamId200ResponseData model = new GetFederationByFederationIdAndTeamId200ResponseData();

    /**
     * Model tests for GetFederationByFederationIdAndTeamId200ResponseData
     */
    @Test
    public void testGetFederationByFederationIdAndTeamId200ResponseData() {
        // TODO: test GetFederationByFederationIdAndTeamId200ResponseData
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'federationType'
     */
    @Test
    public void federationTypeTest() {
        // TODO: test federationType
    }

    /**
     * Test the property 'authType'
     */
    @Test
    public void authTypeTest() {
        // TODO: test authType
    }

    /**
     * Test the property 'authSecretKey'
     */
    @Test
    public void authSecretKeyTest() {
        // TODO: test authSecretKey
    }

    /**
     * Test the property 'endpointBaseurl'
     */
    @Test
    public void endpointBaseurlTest() {
        // TODO: test endpointBaseurl
    }

    /**
     * Test the property 'endpointDatasets'
     */
    @Test
    public void endpointDatasetsTest() {
        // TODO: test endpointDatasets
    }

    /**
     * Test the property 'endpointDataset'
     */
    @Test
    public void endpointDatasetTest() {
        // TODO: test endpointDataset
    }

    /**
     * Test the property 'runTimeHour'
     */
    @Test
    public void runTimeHourTest() {
        // TODO: test runTimeHour
    }

    /**
     * Test the property 'runTimeMinute'
     */
    @Test
    public void runTimeMinuteTest() {
        // TODO: test runTimeMinute
    }

    /**
     * Test the property 'enabled'
     */
    @Test
    public void enabledTest() {
        // TODO: test enabled
    }

    /**
     * Test the property 'enabledAt'
     */
    @Test
    public void enabledAtTest() {
        // TODO: test enabledAt
    }

    /**
     * Test the property 'counter'
     */
    @Test
    public void counterTest() {
        // TODO: test counter
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'deletedAt'
     */
    @Test
    public void deletedAtTest() {
        // TODO: test deletedAt
    }

    /**
     * Test the property 'tested'
     */
    @Test
    public void testedTest() {
        // TODO: test tested
    }

    /**
     * Test the property 'notifications'
     */
    @Test
    public void notificationsTest() {
        // TODO: test notifications
    }

    /**
     * Test the property 'isRunning'
     */
    @Test
    public void isRunningTest() {
        // TODO: test isRunning
    }

}
