/*
 * HDRUK Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.gatewayapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RetrieveWidgetData200Response
 */
public class RetrieveWidgetData200ResponseTest {
    private final RetrieveWidgetData200Response model = new RetrieveWidgetData200Response();

    /**
     * Model tests for RetrieveWidgetData200Response
     */
    @Test
    public void testRetrieveWidgetData200Response() {
        // TODO: test RetrieveWidgetData200Response
    }

    /**
     * Test the property 'datasets'
     */
    @Test
    public void datasetsTest() {
        // TODO: test datasets
    }

    /**
     * Test the property 'dataUses'
     */
    @Test
    public void dataUsesTest() {
        // TODO: test dataUses
    }

    /**
     * Test the property 'scripts'
     */
    @Test
    public void scriptsTest() {
        // TODO: test scripts
    }

    /**
     * Test the property 'collections'
     */
    @Test
    public void collectionsTest() {
        // TODO: test collections
    }

}
