/*
 * HDRUK Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.gatewayapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SearchDatasets200ResponseDataInnerHighlightInner
 */
public class SearchDatasets200ResponseDataInnerHighlightInnerTest {
    private final SearchDatasets200ResponseDataInnerHighlightInner model = new SearchDatasets200ResponseDataInnerHighlightInner();

    /**
     * Model tests for SearchDatasets200ResponseDataInnerHighlightInner
     */
    @Test
    public void testSearchDatasets200ResponseDataInnerHighlightInner() {
        // TODO: test SearchDatasets200ResponseDataInnerHighlightInner
    }

    /**
     * Test the property '_abstract'
     */
    @Test
    public void _abstractTest() {
        // TODO: test _abstract
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

}
