/*
 * HDRUK Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.gatewayapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import uk.ac.hdruk.gatewayapi.model.SearchTools200ResponseDataInnerHighlightInner;
import uk.ac.hdruk.gatewayapi.model.SearchTools200ResponseDataInnerSourceInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SearchTools200ResponseDataInner
 */
public class SearchTools200ResponseDataInnerTest {
    private final SearchTools200ResponseDataInner model = new SearchTools200ResponseDataInner();

    /**
     * Model tests for SearchTools200ResponseDataInner
     */
    @Test
    public void testSearchTools200ResponseDataInner() {
        // TODO: test SearchTools200ResponseDataInner
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'highlight'
     */
    @Test
    public void highlightTest() {
        // TODO: test highlight
    }

    /**
     * Test the property 'uploader'
     */
    @Test
    public void uploaderTest() {
        // TODO: test uploader
    }

    /**
     * Test the property 'teamName'
     */
    @Test
    public void teamNameTest() {
        // TODO: test teamName
    }

    /**
     * Test the property 'typeCategory'
     */
    @Test
    public void typeCategoryTest() {
        // TODO: test typeCategory
    }

    /**
     * Test the property 'license'
     */
    @Test
    public void licenseTest() {
        // TODO: test license
    }

    /**
     * Test the property 'programmingLanguage'
     */
    @Test
    public void programmingLanguageTest() {
        // TODO: test programmingLanguage
    }

    /**
     * Test the property 'programmingPackage'
     */
    @Test
    public void programmingPackageTest() {
        // TODO: test programmingPackage
    }

    /**
     * Test the property 'datasets'
     */
    @Test
    public void datasetsTest() {
        // TODO: test datasets
    }

}
