/*
 * HDRUK Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.gatewayapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import uk.ac.hdruk.gatewayapi.model.UpdateUserDarApplicationRequestAnswersInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UpdateUserDarApplicationRequest
 */
public class UpdateUserDarApplicationRequestTest {
    private final UpdateUserDarApplicationRequest model = new UpdateUserDarApplicationRequest();

    /**
     * Model tests for UpdateUserDarApplicationRequest
     */
    @Test
    public void testUpdateUserDarApplicationRequest() {
        // TODO: test UpdateUserDarApplicationRequest
    }

    /**
     * Test the property 'applicantId'
     */
    @Test
    public void applicantIdTest() {
        // TODO: test applicantId
    }

    /**
     * Test the property 'submissionStatus'
     */
    @Test
    public void submissionStatusTest() {
        // TODO: test submissionStatus
    }

    /**
     * Test the property 'projectTitle'
     */
    @Test
    public void projectTitleTest() {
        // TODO: test projectTitle
    }

    /**
     * Test the property 'approvalStatus'
     */
    @Test
    public void approvalStatusTest() {
        // TODO: test approvalStatus
    }

    /**
     * Test the property 'teamIds'
     */
    @Test
    public void teamIdsTest() {
        // TODO: test teamIds
    }

    /**
     * Test the property 'answers'
     */
    @Test
    public void answersTest() {
        // TODO: test answers
    }

}
