/*
 * HDRUK Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.gatewayapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UpdateQuestionBankQuestionRequest
 */
public class UpdateQuestionBankQuestionRequestTest {
    private final UpdateQuestionBankQuestionRequest model = new UpdateQuestionBankQuestionRequest();

    /**
     * Model tests for UpdateQuestionBankQuestionRequest
     */
    @Test
    public void testUpdateQuestionBankQuestionRequest() {
        // TODO: test UpdateQuestionBankQuestionRequest
    }

    /**
     * Test the property 'sectionId'
     */
    @Test
    public void sectionIdTest() {
        // TODO: test sectionId
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'teamIds'
     */
    @Test
    public void teamIdsTest() {
        // TODO: test teamIds
    }

    /**
     * Test the property 'locked'
     */
    @Test
    public void lockedTest() {
        // TODO: test locked
    }

    /**
     * Test the property 'archived'
     */
    @Test
    public void archivedTest() {
        // TODO: test archived
    }

    /**
     * Test the property 'isChild'
     */
    @Test
    public void isChildTest() {
        // TODO: test isChild
    }

    /**
     * Test the property 'questionType'
     */
    @Test
    public void questionTypeTest() {
        // TODO: test questionType
    }

    /**
     * Test the property 'required'
     */
    @Test
    public void requiredTest() {
        // TODO: test required
    }

    /**
     * Test the property 'forceRequired'
     */
    @Test
    public void forceRequiredTest() {
        // TODO: test forceRequired
    }

    /**
     * Test the property 'allowGuidanceOverride'
     */
    @Test
    public void allowGuidanceOverrideTest() {
        // TODO: test allowGuidanceOverride
    }

    /**
     * Test the property '_default'
     */
    @Test
    public void _defaultTest() {
        // TODO: test _default
    }

    /**
     * Test the property 'guidance'
     */
    @Test
    public void guidanceTest() {
        // TODO: test guidance
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'field'
     */
    @Test
    public void fieldTest() {
        // TODO: test field
    }

}
