/*
 * HDRUK Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.gatewayapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UpdateUserHasRolesRequestRoles
 */
public class UpdateUserHasRolesRequestRolesTest {
    private final UpdateUserHasRolesRequestRoles model = new UpdateUserHasRolesRequestRoles();

    /**
     * Model tests for UpdateUserHasRolesRequestRoles
     */
    @Test
    public void testUpdateUserHasRolesRequestRoles() {
        // TODO: test UpdateUserHasRolesRequestRoles
    }

    /**
     * Test the property 'read'
     */
    @Test
    public void readTest() {
        // TODO: test read
    }

    /**
     * Test the property 'create'
     */
    @Test
    public void createTest() {
        // TODO: test create
    }

}
